### ISSUE TITLE
core_login_handlers does not exist in 4.3

### ISSUE THREAD

**Issue by aStonedPenguin** [Lavoaster/IP.Board-Steam-Authentication-Method#110]
On a fresh install it appears it was changed to `core_login_methods` with a slightly different structure.

**Comment by madman32395** [comment]
I've been saying that in the issues where he references... It's not a 4.3 update he's doing, it's just a haxy fix for existing clients. Doesn't fix it for new installations.

**Comment by Exonical** [comment]
Yeah, I found it doesn't work on new installs because it doesn't create the Row needed in MySQL for it. I managed to get it working for registrations by adding the MySQL Field manually, doesn't show up on users profile though

**Comment by kacx9c** [comment]
An app exists in the IPS MP with 4.3 compatibility
