### ISSUE TITLE
How to fix steam login 2.0.4 manually without upgrading to IPS 4.2-4.3?

### ISSUE THREAD

**Issue by WeirdPhrog** [Lavoaster/IP.Board-Steam-Authentication-Method#116]
I have IPS v4.1.19.4 but I don't have time to fix all styles and plugins with upgrading to 4.2 and above. How to fix steam login 2.0.4 manually without upgrading to 3.0.0, which requires IPS 4.2-4.3?

**Comment by WeirdPhrog** [comment]
I put this:

	/**
	 * Get title
	 *
	 * @return	string
	 */
	public static function getTitle()
	{
		return 'Steam';
	}

And now everything is fine. Is it okay?

**Comment by itsAliAvali** [comment]
I'm gonna be straight up. You have time to potentially figure this out...
But not time to update your board to get the proper update for your steam
login... Just because you "don't" have the time to update styles...
