### ISSUE TITLE
[Issue]Activate account automatically

### ISSUE THREAD

**Issue by Nerus87** [Lavoaster/IP.Board-Steam-Authentication-Method#124]
Hey, I have a problem with this plugin.

[Story]
After the user registers - the first login and providing some information like email address and accept the rules, an administrator is forced to approve the user manually. But I think there no sense because the user is authorized from the steam.

[Solution]
So maybe the correct way will be to add the switch to the plugin settings with the default option "authorize automatically".

**Comment by rubiksw** [comment]
Make sure you have toggled 'No validation required' in Login & Registration --> Registration. Also if you have enabled Spam Prevention this could also flag your users for manual review.

**Comment by Nerus87** [comment]
![image](https://github.com/LavaToaster/IPS-SteamLoginMethod/assets/3099926/92b7e05a-4ba9-4d85-ab06-4faf1c7f219b)
![image](https://github.com/LavaToaster/IPS-SteamLoginMethod/assets/3099926/9bc19269-942c-4dc4-82f9-330a4f605209)
So I should disable Spam Prevention?

**Comment by rubiksw** [comment]
Disabling spam filter or at least adjusting it so that it doesn't flag users for manual review solved the issue for me.

**Comment by Nerus87** [comment]
Thanks, can be closed for now.
