### ISSUE TITLE
Using https and creating an account

### ISSUE THREAD

**Issue by Fopje** [Lavoaster/IP.Board-Steam-Authentication-Method#19]
When I have https logins enabled for my forum I get the same issue as reported in #15 
Is there already a fix for this

and after disabling the https and someone creates an account it seems it can't handle the custom forms. I have a forum for steamid and skypename, which arent required, it keeps showing up after trying to create a new account. after removing them from showing on the registration for, it just shows a page with "There are still a few things required before making your account" with no steam or skype box this time, but clicking the create buttons also doesn't do anything.

**Comment by Lavoaster** [comment]
Is this still occurring? If so, could you provide a link to your community. If you wish that to be private you can email me at adam@lavoaster.co.uk.

**Comment by Lavoaster** [comment]
As there has been no response in this issue for a month, I'll be closing this issue.
