### ISSUE TITLE
Login with steam just hangs

### ISSUE THREAD

**Issue by yusuf-a** [Lavoaster/IP.Board-Steam-Authentication-Method#20]
when a user clicks "sign on with steam", it shows "waiting for http://mydomain.com" at the bottom, and that something is loading, but nothing ends up happening.

**Comment by wattz1979** [comment]
Same issue here installed it with 3.4.7 ipb and followed instructions and just hangs on sign in

**Comment by Lavoaster** [comment]
Sorry for the long response time.

I have two questions for you two answer

* Is this still an issue?
* Has it always hanged?

**Comment by Lavoaster** [comment]
As there hasn't been any response on this in a month, I'll be closing this issue.
