### ISSUE TITLE
Can't upgrade to 4.0.7 with Steam

### ISSUE THREAD

**Issue by jonathanbloom** [Lavoaster/IP.Board-Steam-Authentication-Method#21]
I get the following error when trying to update to 4.0.7 with Steam. IPS told me to contact you.

NO_TEMPLATE_FILE - /home/DOMAIN/public_html/admin/upgrade/html/plugins/steam.phtml

**Comment by Lavoaster** [comment]
If you disable the ability to login to the ACP from steam then you will be able to upgrade.

I've got a fix in the pipeline :)

**Comment by jonathanbloom** [comment]
Thanks, that worked! :)

**Comment by xianthe** [comment]
I did this and with 4.0.7, (disable in ACP and re-enable) and when i reable I still have the  NO_TEMPLATE_FILE error. Any clues?

**Comment by madman32395** [comment]
Because the fix is currently not released. This is an issue with the
plugin. Nothing that ipb upgrade will fix. Just disable it when you upgrade
until lavo fixes it.

**Comment by xianthe** [comment]
Thanks I am new to IP.Board v4 and was unclear if this work around actually allowed you to proceed or just let you upgrade. I am actually trying to just research login handlers and IP Connect in any way possible right now so any help is appreciated. Documentation on v4 is very slim for someone who hasnt used IPB in years.

**Comment by cpaneljesse** [comment]
When do you plan to resolve this issue? It appears to affect every upgrade :(

**Comment by Lavoaster** [comment]
From what I'm aware of, this is supposed to no longer be an issue onwards from 4.0.8.

**Comment by Lavoaster** [comment]
Is anyone aware of if this is still occurring in later versions of the IP Suite?

**Comment by madman32395** [comment]
I personally have not have had this issue since the last few updates from IPS. I think it is safe to close and if issues reoccur, can reopen.
