### ISSUE TITLE
Redirect Doesn't Work When Signing In

### ISSUE THREAD

**Issue by AutoJukebox** [Lavoaster/IP.Board-Steam-Authentication-Method#22]
So when ever a user on my forums trys to login to takes them to steam login and they login and it doesn't log them in... It just takes them back to the steam page.

I'm running IPB 3.4.7
Windows Server with IIS Webserver
I'm using Steam Login Method 1.1.2

Thanks

~Autojukebox

**Comment by madman32395** [comment]
If I remember correctly this is an issue with IIS; I cant remember what I did to fix it, but I ended up switching to apache and majority of all my headaches went away.

**Comment by AutoJukebox** [comment]
Hopefully it's not a issue with IIS, I haven't had problems with IIS till this.

**Comment by madman32395** [comment]
What website is this at? Are you able to contact me on steam? www.steamcommunity.com/id/madman32395

**Comment by madman32395** [comment]
@AutoJukebox What version of the steam login plugin are you using with 3.4.7?

**Comment by AutoJukebox** [comment]
1.1.2 i believe

**Comment by AutoJukebox** [comment]
http://www.astralgaming.info/forums/ is my website

**Comment by madman32395** [comment]
Found that IIS does not cooperate friendly. Had @AutoJukebox switch to apache and besides having the plugin work, found that the website was responding much smoother on Apache rather than IIS.
