### ISSUE TITLE
login_handler_steam rejected the details provided. Please check the details you provided have been entered correctly and try again.

### ISSUE THREAD

**Issue by JMV1234** [Lavoaster/IP.Board-Steam-Authentication-Method#23]
I get this error message every time I try to enter my steam API key, I've tried to revoke it and get a new one and the error comes up again

**Comment by Lavoaster** [comment]
Do you have curl enabled?

**Comment by JMV1234** [comment]
No, do I need it?

**Comment by JMV1234** [comment]
I correct myself, I re-checked and its enabled.

**Comment by madman32395** [comment]
What server is this running on? Any firewalls blocking communication?

**Comment by JMV1234** [comment]
No firewalls, it's hosted by x10hosting.com. I've confirmed with them that
curl is working.

**Comment by Lavoaster** [comment]
Are you on their shared hosting platform?

**Comment by JMV1234** [comment]
Yes. Does this plugin require anything in particular from the server?

**Comment by madman32395** [comment]
hmm. Possible for me to take a peek at the setup? Can you contact me on steam? www.steamcommunity.com/id/madman32395

**Comment by madman32395** [comment]
The weird part is that I have my Curl turned off/commented out and my login still works fine.

**Comment by madman32395** [comment]
@JMV1234 what web server are you running this on?

**Comment by JMV1234** [comment]
I changed webhost and it worked like a charm. Thanks for all the help guys! Still have no idea what was wrong.

**Comment by madman32395** [comment]
@JMV1234 random question but was it on IIS?

**Comment by JMV1234** [comment]
Not sure what IIS is, the webhost was x10hosting

**Comment by madman32395** [comment]
ah no problem. I am glad its working for you. 

I've noticed that even IPS says they have issues with free hosts as well. A lot of the times they inject html ads and other stuff onto the site, and don't do it properly so stuff looks/acts all crazy.

I did look around at x10hosting and they are on Lightspeed (apache drop in), with gzip and a bunch others running. So I'm sure something they were running was bugging you up :+1:

**Comment by cpaneljesse** [comment]
I am getting this error all of a sudden on my installation even though it's been working for a few months. Nothing has been changed on our server that I can think of that would affect this.

Running LSPHP with:

Server version: Apache/2.4.16 (Unix)
PHP 5.4.45 (cli) (built: Sep 12 2015 22:15:19)
