### ISSUE TITLE
Settings not showing in AdminCP

### ISSUE THREAD

**Issue by Hazz14** [Lavoaster/IP.Board-Steam-Authentication-Method#24]
I've tried installing the Steam Login plugin for IPB4, but the plugin doesn't appear under Login Handlers in the Admin CP. I've uploaded the files and installed it with the .xml file, but no luck unfortunately.

Any ideas?

**Comment by madman32395** [comment]
Sounds like you have installed it so far correctly. Have you looked under System>Settings>Login Handlers   ... Steam should be under there, with the pencil logo.

**Comment by Hazz14** [comment]
Nope, doesn't appear in the Login Handlers section.

**Comment by madman32395** [comment]
hmm interesting. I am hoping to be back on my home computer in about 20ish minutes. Would you mind if I took a peak?

**Comment by Hazz14** [comment]
What will you need? I won't be able to give access until later.

**Comment by madman32395** [comment]
hit me up on steam when youre ready. http://steamcommunity.com/id/madman32395
Probably be looking at ACP access and FTP; and your steam API key. (don't post your keys or credentials here; do privately)

**Comment by madman32395** [comment]
Saw that the server did not create a login handler which caused the issue of not showing a settings menu for steam. The server also did not generate a new collumn for steamids. Manually ran queries to resolve this issue. Would recommend following the recommended section of the system check from ACP>System>Support>Support>System Check (button located on top of page; recommended fixes on the bottom of the System Check)

**Comment by Hazz14** [comment]
All sorted - thanks for the help :+1:

**Comment by mnewton91** [comment]
I've got this problem also - Are you able to assist me? or post the edits you made on the missing table entries?

**Comment by Hazz14** [comment]
The reason it wasn't creating the tables was because the versions of PHP/MYSQL were old. I'm not sure what edits madman made manually though.

**Comment by madman32395** [comment]
@mnewton91 you able to hit me up on steam so I could take a peak?

**Comment by mnewton91** [comment]
I've added you @madman32395
