### ISSUE TITLE
IIS issues with plugin

### ISSUE THREAD

**Issue by madman32395** [Lavoaster/IP.Board-Steam-Authentication-Method#25]
There are different issues arising; ranging from issues like #23 and #22 ; This is an issue with IIS somewhere, but the current work around is trying to switch to Apache or another web server. 

See current workaround and free hosting disclaimer in the readme 39e55a594a816d44b149779bfd4e4ef60723a438

**Comment by Lavoaster** [comment]
Unless anyone is willing to pick up the work to do this, I will not be looking into this issue.
