### ISSUE TITLE
IPB Steam login issue.

### ISSUE THREAD

**Issue by OMGLent** [Lavoaster/IP.Board-Steam-Authentication-Method#26]
So I'm having an issue with getting it to work properly. It shows up completely fine however after the login through steam page it simply redirects you back to the homepage. This is the exact link >

https://perspectiverp.com/forums/steam.php?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=error&openid.error=realm+and+return_to+do+not+match

I'm currently using IPB 3.4.8

**Comment by madman32395** [comment]
@OMGLent 
What host do you use?
What WebServer are you running? 
I do notice you use CloudFlare (firewalling), do you continue to have this issue if you temporary disable the firewall?

**Comment by madman32395** [comment]
also, misleading verification screen.. lol appears like a ban. https://drive.google.com/file/d/0B0mBb9QuGv84QnVzQmxyMHJsdzQ/edit?usp=drivesdk

**Comment by OMGLent** [comment]
I use Xenon Servers running Apache Version 2.2.29 and the issue is still a problem when I have disabled my cloud-flare firewall.

**Comment by OMGLent** [comment]
@madman32395 you will need to verify your account before you can access the members list.

**Comment by OMGLent** [comment]
@madman32395 nvm It appears you have been banned that's strange...

**Comment by madman32395** [comment]
Which version of the plugin are you using? also It wont even let me view the forums main page, have not received an validation email.

**Comment by OMGLent** [comment]
I'm using version 1.1.1 or the latest version as I uninstalled and tested it last night. It said you were banned because you were spammer or something. Anyway you're currently unbanned.

**Comment by madman32395** [comment]
hmm. guess it doesnt like my work internet xD... 

Has the steam plugin ever worked?

**Comment by OMGLent** [comment]
Yes it worked awhile back and I'm not sure what may have caused it to do this . One thing I have noticed is that my email wrapper is no longer working anymore as well. So I presume it might be a corrupted fire somewhere. I already manually reinstalled IP.B 3.4.8 to make sure the core files were not harmed or broken.

**Comment by madman32395** [comment]
okay, reason I ask, if its uninstalled; most installations end up nuking the steamid column in their member table (requiring everyone to relink steam; unless backup of that table was done and restored)

Would you be available on steam? I would like to take a deeper look. Something just doesn't seem right.

**Comment by OMGLent** [comment]
Here is my steam if that's what your asking for.
http://steamcommunity.com/id/TracedPentic/

**Comment by madman32395** [comment]
Ended up upgrading from 348 to 4091; installed 4.x steam login, everything working. Did some security best practises.
