### ISSUE TITLE
Plugin installs but Login Handler doesn't show up

### ISSUE THREAD

**Issue by sahaka** [Lavoaster/IP.Board-Steam-Authentication-Method#27]
I have just purchased IPS and got it working. Then I went to install this: https://community.invisionpower.com/files/file/7555-sign-in-through-steam-ipb4/

The plugin installs correctly without errors. But there is no edit option and it does not show up on the Login Handler page. I feel like I must be doing something wrong but I have followed the directions and it still doesn't work. Any help would be greatly appreciated.

**Comment by madman32395** [comment]
Hit me up on steam and ill take a peak if ya want, http://steamcommunity.com/id/madman32395
Would need ACP, FTP, SteamAPI key; DO NOT post that information here, share privately.

Thanks.

**Comment by sahaka** [comment]
Ok I will add you on steam keep an eye out for http://steamcommunity.com/id/defriscod

**Comment by madman32395** [comment]
Upload was not in correct directories, removed from wrong areas and reuploaded files. Fixed.
