### ISSUE TITLE
Rewrite URLs

### ISSUE THREAD

**Issue by aStonedPenguin** [Lavoaster/IP.Board-Steam-Authentication-Method#28]
Logging in does not seem to work with Rewrite URLs and Force Friendly URLs enabled

**Comment by Lavoaster** [comment]
Can you double check you've got the right .htaccess file or relevant nginx configuration setup correctly and that your IP Suite is working correctly. 

I don't know what would use a rewritable URL in this plugin that wouldn't be controlled by the IPS Suite.

Additionally, what version are you using?

**Comment by madman32395** [comment]
Not saying I have a perfect setup, but I have rewrite turned on and my logins work.
https://drive.google.com/file/d/0B0mBb9QuGv84OEdId0VKLVpkRVE/view?usp=drivesdk

When setting up rewrite, did you make sure to download/edit htaccess that is under the toggle switch?

**Comment by madman32395** [comment]
Notes: IPB4 ; Nginx

**Comment by Lavoaster** [comment]
Is this still an issue?

**Comment by Zhao-Steven** [comment]
Hey,

I am having the same issue with an Nginx server with the following configuration for write:
```
	location / {
	    try_files  $uri $uri/ /index.php;
	}
	location ~^(/page/).*(.php)$ {
	    try_files  $uri $uri/ /index.php;
	}
```

Turning off this and friendly url rewriting and the plugin will work.

**Comment by aStonedPenguin** [comment]
@Zhao-Steven Turning off "Force Friendly URLs" works as a temporary work around.

**Comment by Lavoaster** [comment]
Due to the fact this is not a plugin issue, I will be closing off this issue.
