### ISSUE TITLE
Making this plugin only registration/login option

### ISSUE THREAD

**Issue by cpaneljesse** [Lavoaster/IP.Board-Steam-Authentication-Method#29]
Is it possible to disable the default ipb registration and make it so you can only register to our forums with your STEAM login?

**Comment by Lavoaster** [comment]
AFAIK, This has been done without the need for anything plugin specific.

What IPB version are you using?

**Comment by cpaneljesse** [comment]
We are using the latest version of IPB4. It has both enabled, however, if we disable new user registration, it also disables the steam one as well.

**Comment by Lavoaster** [comment]
You should be able to disable the login handler for username and passwords. I think it's called Internal, could be wrong. Basically, all you need to do is ensure that Steam is the only enabled login method.

**Comment by cpaneljesse** [comment]
It doesn't allow you to disable internal, is the problem.

**Comment by aStonedPenguin** [comment]
Best you can do is edit it out of the template.

**Comment by madman32395** [comment]
4.3 you can disable the main (Standard) login handler, which as long as you don't have other handlers that use the login form, it will hide the user/pass form without needing to do template edits.

(Verified with 4.3 beta 3)
