### ISSUE TITLE
Cannot find Steam in Login Handlers

### ISSUE THREAD

**Issue by usedragon** [Lavoaster/IP.Board-Steam-Authentication-Method#30]
I installed the Sign in through Steam - IPB4 2.0.0 on a IPS4 4.0.12.1 and no matter how much i tried to look in Login Handlers Steam isn't popping up. Uninstall/Install doesn't pop up.

**Comment by madman32395** [comment]
I'll be back in town in about an hour or so. If you want you can add me on
steam and I'll look at this for you.
Http://steamcommunity.com/Id/madman32395

**Comment by madman32395** [comment]
@usedragon are you still having an issue?

**Comment by madman32395** [comment]
@usedragon No response over 13 days, Closing ticket.
