### ISSUE TITLE
IPS4 French Sign In

### ISSUE THREAD

**Issue by Nukeproof-Mega** [Lavoaster/IP.Board-Steam-Authentication-Method#31]
Hey there my members are saying that they are being signed into the French site and not the UK version, is this an easy fix?

**Comment by madman32395** [comment]
This as far as I know wouldn't be related to the steam plugin for ips. This would most likely be a geolocation issue on steam itself.

personally sometimes I get flagged into Germany even though I'm here in the states.

**Comment by Lavoaster** [comment]
Ditto what @madman32395 said. This plugin does no geolocating at all.
