### ISSUE TITLE
Installed Correctly but not shown on login handlers

### ISSUE THREAD

**Issue by MyBottingVPS** [Lavoaster/IP.Board-Steam-Authentication-Method#32]
I installed all files in upload correctly into the directories they belonged in, in my root folder. I installed the plugin correctly. However, when I go to login handlers, steam is not shown.

**Comment by madman32395** [comment]
I am currently out of town but can assist in fixing this for you. I am
expected back in town possibly 845-915pm cst.

**Comment by madman32395** [comment]
@MyBottingVPS When is a good time for you to meet up?

**Comment by BOLVERIN** [comment]
same problem

**Comment by BOLVERIN** [comment]
up php to 5.4. not helped

**Comment by deanm1990** [comment]
same issue , cannot see in login handler :(

**Comment by BOLVERIN** [comment]
look at  DB
in tables core_login_handlers not found info about Steam like this:
('Steam', 1, '{"steam_apikey":"","use_steam_name":true}', 10, 0)

**Comment by BOLVERIN** [comment]
also I not found in Theme any files in Login directory

**Comment by Lavoaster** [comment]
Did you all install the hook?

**Comment by BOLVERIN** [comment]
hook? I use instruction from README.md 
on example.com all ok
on example2.com/forum — have problem

**Comment by BOLVERIN** [comment]
maybe need some additional info? some hours I'm here

**Comment by deanm1990** [comment]
got it working now :) 

thankyou

 

 

 

-----Original Message-----

**Comment by Lavoaster** [comment]
@BOLVERIN Discarding configuration, there are two main things you need to do. Upload all files in the `upload/` directory (Step 1) and import the hook / plugin into IPB (Steps 2 and 3).

**Comment by BOLVERIN** [comment]
with upload/ or form /upload?

**Comment by Lavoaster** [comment]
All files _in_ the folder not the upload folder itself.

**Comment by BOLVERIN** [comment]
I do this. Like I say before: I use this plugin for two forum. first — all ok. second — have a problem

**Comment by Lavoaster** [comment]
When on your production installation, do you have the sign in through steam plugin installed?

Can you screenshot it?

**Comment by BOLVERIN** [comment]
https://yadi.sk/i/AJizKkReix4iX plugin page
https://yadi.sk/i/p2R2a5R6ix4k3 login handlers page

**Comment by Lavoaster** [comment]
Is this a new install of the plugin or are you upgrading your forum from 3.4?

**Comment by BOLVERIN** [comment]
new install

**Comment by Lavoaster** [comment]
Can you remove the steam plugin and then reinstall it?

**Comment by BOLVERIN** [comment]
reinstall, reupload, deleting and then upload + install. I'm alredy try it

**Comment by Varshney** [comment]
I'm also having the same issue. When I installed the plugin for the work forums it was flawless and just worked straight off, but when I upgraded my forums to IPS4 then installed this plugin and set it to enabled, it just doesn't show up under the login handlers, the exact same images as Bolverin.

I can't understand why this would work on one and not the other. Very strange indeedy.

**Comment by msanders-lg** [comment]
I can confirm that I am also having this is issue, running a fresh install of 4.0.9.2

**Comment by madman32395** [comment]
@msanders-lg please upgrade to the latest 4.0.13.1 and see if the issue continues with a reupload of the add-on as well.

**Comment by Varshney** [comment]
I have already been running 4.0.13.1 so it's definitely not the version number.

**Comment by BOLVERIN** [comment]
update to 4.0.13.1 helped me

**Comment by Varshney** [comment]
I've tried uninstalling and reinstalling and still it doesn't work. I then have tried a fresh test installation of 4.0.13.1 and even after uploading the files and installing the XML it doesn't show up in the login handlers yet it says that the plugin is installed.

Is there a way to manually add the options to the login handler screen?

**Comment by madman32395** [comment]
@Varshney yes

**Comment by JesperGrip** [comment]
Hey im currently having the same problem with my plugin i'm running the latest version of IPS and it doesn't appear in login handlers

**Comment by Varshney** [comment]
@madman32395 - Is it possible you can run us through how we can manually do this please. That way if anyone else has the same issues then they'll know what to do in the future too.

**Comment by madman32395** [comment]
@Varshney  Sorry for the delay, make sure to backup the database or the table affected, and check with core_login_handlers and see what is your highest login_order then +1 ; don't forget to edit the query for match for prefix (if applicable), and to edit the value for login_order. If needed too, I can assist in getting this working for you as well. (can be done solely through the Admin ControlPannel of IPB

INSERT INTO core_login_handlers (login_key, login_settings, login_order, login_acp, login_enabled)
VALUES ('Steam','{"steam_apikey":"","use_steam_name":true}','#*check2see what is highest login_order then +1','0','1');


@JesperGrip Check in core_login_handlers and see if you have steam in there.
