### ISSUE TITLE
login_handler_steam rejected the details provided. Please check the details you provided have been entered correctly and try again.

### ISSUE THREAD

**Issue by cpaneljesse** [Lavoaster/IP.Board-Steam-Authentication-Method#33]
I am getting this error all of a sudden on my installation even though it's been working for a few months. Nothing has been changed on our server that I can think of that would affect this.

Running LSPHP with:

Server version: Apache/2.4.16 (Unix)
PHP 5.4.45 (cli) (built: Sep 12 2015 22:15:19)

**Comment by madman32395** [comment]
interesting. When is a good time to meet up to look into this?

**Comment by madman32395** [comment]
Closing as no response was given in over 30 days
