### ISSUE TITLE
[Suggestion] Display Steam Profile

### ISSUE THREAD

**Issue by critfest** [Lavoaster/IP.Board-Steam-Authentication-Method#34]
After a user associates their IPB account with their steam account, it would be absolutely awesome if this plug-in inserted a simple link to the IPB profile, which would point to their SteamCommunity profile!  Thank you in advance for your consideration!  Love the plugin though by the way!  ;)

**Comment by critfest** [comment]
Or even a steam offline/online badge type thing where it could tell people in the forums where a user was on or offline for steam and possibly what game they are currently playing.  I know something like this was done for version 3.x of IPB but I am not sure if it's possible to do with this or maybe as a separate plugin.  Thanks again for your consideration.

**Comment by Lavoaster** [comment]
Thanks for the idea, however, after some thought this outside of what the scope of what this plugin should support.
