### ISSUE TITLE
Something went wrong. Please try again

### ISSUE THREAD

**Issue by boLekc** [Lavoaster/IP.Board-Steam-Authentication-Method#35]
uploaded files, installed plugin, activated plugin / login handler  and added the api key but everytime when i try to login i get

Something went wrong. Please try again.

**Comment by madman32395** [comment]
I just shut down for the night. But can take a look for you when I wake.

**Comment by boLekc** [comment]
have reinstalled the github version and get now this error

An error occurred while processing your request.

**Comment by madman32395** [comment]
@boLekc Im alive! lol ; you available?

**Comment by boLekc** [comment]
sure ^^

**Comment by madman32395** [comment]
http://steamcommunity.com/id/madman32395/

**Comment by madman32395** [comment]
Could not diagnose; was unable to get proper credentials to find issue.

**Comment by madman32395** [comment]
@Lavoaster ; This is on a linux install with apache, php 5.6.14

I uninstalled the plugin that he had, and reinstalled a working version that I had locally. Both him and I had same results. When attempting to enter steam api key into settings, we get "login_handler_steam rejected the details provided. Please check the details you provided have been entered correctly and try again."

But when editing sql, changing the default {"steam_apikey":"","use_steam_name":true} to {"api_key":"","use_steam_name":true} ; then tried to save api key and it worked this time.

but logins were still not allowing. Checked error.log for anything, nothing pointing to the login or steam plugin

**Comment by Lavoaster** [comment]
Is curl enabled?

**Comment by madman32395** [comment]
He's working on getting that going. His test site worked fine out the gate.
But live i dont think has what test did.

Forgot to write that before my ISP kicked me off for maint.

**Comment by madman32395** [comment]
certain plugins are out of date: cURL running less than version 7.36  (currently on 7.21.0) ;; MySQL currently on 5.5.45-37.4-log , IPS recommends 5.6.0 or higher ;;PHP setting for suhosin.max_vars is unable to be read by system check, but is currently set to 6144 for all suhosin.*.max_vars

He did have a test site that worked, but is unable to continue with that host, and unable to talk to current provider about coping that configuration.

**Comment by madman32395** [comment]
Got user setup on host that fits IPS requirements, and installed and verified IPS 4.1.0 and Steam Plugin (2.0.0); @boLekc is now up and running, he will take care of data transfer from old host to new host. 

--Issue related to whatever host he was using; moved to GoDaddy (met requirements and was able to communicate back to valve for steam login) and is working.
