### ISSUE TITLE
Cache Avatars

### ISSUE THREAD

**Issue by aStonedPenguin** [Lavoaster/IP.Board-Steam-Authentication-Method#36]
Would it be possible to add an option to cache avatars? Steam is stupid slow sometimes.

**Comment by madman32395** [comment]
0ffac63bd81d1bfd9c80d23a8d3695c62133ee95 Added in Cache to datastore, and db auto points to it instead of valve's CDN

Just reupload, applications\core\sources\profilesync\steam.php
