### ISSUE TITLE
Steam API Key

### ISSUE THREAD

**Issue by marcelotk15** [Lavoaster/IP.Board-Steam-Authentication-Method#37]
Hi,
I read others same issues, but any help me.

My system:
Ubuntu: Ubuntu 14.04.3;
Apache: Apache/2.4.7;
PHP: PHP 5.6.14-1+deb.sury.org~trusty+1 (cli);
cURL: Enabled;
IPS: 4.0.13.1 (100045);
and i use CloudFire.

My error is: login_handler_steam rejected the details provided. Please check the details you provided have been entered correctly and try again.

**Comment by madman32395** [comment]
@marcelotk15 available? http://steamcommunity.com/id/madman32395

**Comment by madman32395** [comment]
@Lavoaster Ran the IPB4 System Check, user meets requirements 100%, cURL is enabled and meets/exceeds required for IPS as well.  ; user also uses CloudFlare, had him enter steamAPI ip addresses into outbound firewall from valve as troubleshoot. No Change.

**Comment by marcelotk15** [comment]
Really i don't know what is wrong. I put manually infos in database (steam API and steamid). Nothing... don't sync, won't login. 
Thanks for support in steam @madman32395!

**Comment by madman32395** [comment]
once a fix is found for this one might be possible fix for #35

**Comment by marcelotk15** [comment]
Now is working.
I formated my VPS and install packages (php. apache and etc) with Zpanel scrip https://github.com/zpanel/installers
