### ISSUE TITLE
500 Error after Steam Login on Redirect

### ISSUE THREAD

**Issue by assault04** [Lavoaster/IP.Board-Steam-Authentication-Method#38]
I set everything up normally and attempted to sync my existing account with my steam account.

Running Apache on CentOS. I can login to Steam and when it redirects, it attempts to go to this URL:

http://www.initial.gg/applications/core/interface/steam/auth.php?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561197960930197&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561197960930197&openid.return_to=http%3A%2F%2Fwww.initial.gg%2Fapplications%2Fcore%2Finterface%2Fsteam%2Fauth.php&openid.response_nonce=2015-11-04T19%3A36%3A48ZJV5uN1bXNPtuQzpa6uYDwFd4KCU%3D&openid.assoc_handle=1234567890&openid.invalidate_handle=ucp&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cinvalidate_handle&openid.sig=hr0eqlPY7AOt%2F%2BbA0TzAEzky0n4%3D

I get the generic 500 Internal Server Error:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@initial.gg to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by madman32395** [comment]
hi @assault04 , what IPS version are you currently running? and What version of the login plugin are you using (2.0.0 or the prerelease 2.0.1?)

**Comment by assault04** [comment]
Currently running v2.0.0 of the plugin on IPS v4.1.2

**Comment by madman32395** [comment]
If you could, can you update to latest ips release? 4.1.3.1

**Comment by assault04** [comment]
Updated to the latest release, still the same issue.

**Comment by madman32395** [comment]
interesting. Add on steam and I could take a deeper look if you're up for it?

**Comment by madman32395** [comment]
http://steamcommunity.com/id/madman32395

**Comment by madman32395** [comment]
Permissions were not set correctly for parent/child folder. Needs Read access, recommend (755)
Issue was self-resolved.
