### ISSUE TITLE
Redirect Loop Error

### ISSUE THREAD

**Issue by ucjohn** [Lavoaster/IP.Board-Steam-Authentication-Method#39]
Alot of our members are getting Redirect loop errors when trying to sign up with steam Login handle.

**Comment by madman32395** [comment]
What web server are you using? Are you up to date with IPS version? What
3rd party plugins and apps are installed?

**Comment by ucjohn** [comment]
Yes I'm running the very latest version of IPB.. VizionDev app is the 3rd party Application but it shouldn't conflict with it. I'm stumped I asked some of the IPB devs they said they can't look at it due to it being 3rd party. I disable the steam login handle the issue goes away.. Enable it and it returns...

**Comment by madman32395** [comment]
I'm almost done watching Pixels. If you would like I could take a look if
that's okay with you?
Http://steamcommunity.com/id/madman32395

**Comment by madman32395** [comment]
Found to be a compatibility issue with https://community.invisionpower.com/files/file/7482-terms-of-service/

I sent Adriano a message asking about it.

**Comment by madman32395** [comment]
@ucjohn Was told that all 3rd party login methods are incompatible 
https://community.invisionpower.com/topic/410868-terms-of-service/?do=findComment&comment=2600014
