### ISSUE TITLE
No login handler in IPB 4.1

### ISSUE THREAD

**Issue by MightySCollins** [Lavoaster/IP.Board-Steam-Authentication-Method#40]
Hi

I have tried to install on IPB 4.1 and I cannot see the steam login handler in my list.
It seemed to work well on a IPB 4 install.

Am I doing anything wrong? Thanks in advanced

**Comment by madman32395** [comment]
@MightySCollins can you check your core_login_handlers table and see if you have steam listed in there?

**Comment by MightySCollins** [comment]
:( I am sure I did it right... It worked fine in 4.0

Steam is in the `core_login_handlers` table and I have even added the config for it manually but it still does not show up in the Login Handlers page and even if I enable it in MySQL it does not show. 

I have also tried it again on a fresh test install with no luck.

**Comment by Lavoaster** [comment]
Did you upload the files?

**Comment by madman32395** [comment]
@MightySCollins What IPS version are you on? and what PHP version, and do you have cURL enabled?

Also like lavo asked, did you upload the files into the correct spot?

**Comment by MightySCollins** [comment]
Yes I did but you where right it was my fault :(
It seems that I uploaded them as blank files, sorry to waste your time and thanks for the good plugin.
