### ISSUE TITLE
members are broke after the new ip board update 

### ISSUE THREAD

**Issue by taman1990** [Lavoaster/IP.Board-Steam-Authentication-Method#41]
So after i updated my forum to the latest one 4.1.4 some of the members are completely broke 
all of their posts topics hided and they are restricted from posting, receiving messages visiting account settings changing profile and everything else its like they are banned but worse i cant even send this members a message because they ant receive messages and the worse part is i cant change edit or doing anything else on this members at ACP nothing can be changed 
so after days of arguing with IPS support with a ticket finally they told me that the problem is with steam plugin i have installed 
this is the error log

Thu, 03 Dec 2015 11:55:00 +0000 (Severity: 2)
50.28.55.154 - http://hellshammers.net/forum/index.php?/settings/
RuntimeException
0: BAD_JSON
#0 /home5/xxxxxxx/public_html/forum/applications/core/sources/ProfileSync/Steam.php(40): IPS\Http\_Response->decodeJson()
#1 /home5/xxxxxxx/public_html/forum/applications/core/sources/ProfileSync/Steam.php(91): IPS\core\ProfileSync\_Steam->userData()
#2 /home5/xxxxxxx/public_html/forum/system/Theme/Theme.php(692) : eval()'d code(6220): IPS\core\ProfileSync\_Steam->name()
#3 [internal function]: IPS\Theme\class_core_front_system->settingsOverview(Array)
#4 /home5/xxxxxxx/public_html/forum/system/Theme/SandboxedTemplate.php(57): call_user_func_array(Array, Array)
#5 /home5/xxxxxxx/public_html/forum/applications/core/modules/front/system/settings.php(115): IPS\Theme\_SandboxedTemplate->__call('settingsOvervie...', Array)
#6 /home5/xxxxxxx/public_html/forum/applications/core/modules/front/system/settings.php(115): IPS\Theme\SandboxedTemplate->settingsOverview(Array)
#7 [internal function]: IPS\core\modules\front\system\_settings->_overview()
#8 /home5/xxxxxxx/public_html/forum/applications/core/modules/front/system/settings.php(55): call_user_func(Array)
#9 /home5/xxxxxxx/public_html/forum/system/Dispatcher/Controller.php(94): IPS\core\modules\front\system\_settings->manage()
#10 /home5/xxxxxxx/public_html/forum/applications/core/modules/front/system/settings.php(35): IPS\Dispatcher\_Controller->execute()
#11 /home5/xxxxxxx/public_html/forum/system/Dispatcher/Dispatcher.php(129): IPS\core\modules\front\system\_settings->execute()
#12 /home5/xxxxxxx/public_html/forum/index.php(13): IPS\_Dispatcher->run()
#13 {main}

maybe an update to fix ?
thank you

**Comment by Lavoaster** [comment]
If you disable the plugin, does everything work?

**Comment by madman32395** [comment]
do you also use any third party steam management application/plugins?

**Comment by taman1990** [comment]
no i dont use any other steam apps only steam login handler 
and i have already tried to disable the plugin and steam login handler to see if it fixes the issue but no hope
the only way to fix this broken members is creating a new account for them and merging with the broken ones :/ i had to do that for a several active members

**Comment by madman32395** [comment]
are the members being flagged as spammer or being banned?

**Comment by taman1990** [comment]
normal members, no spams no banned
they cant visit their account settings this error shows up when they click account settings 
https://www.invisionpower.com/clients/index.php?app=nexus&module=support&section=redirect&url=https%3A%2F%2Fi.gyazo.com%2F1240d313d5d17dd6c7cfecdc118e8331.png&key=4b893f4a240f187be05b6fe66d1d441028cbcc70&resource=1

in ACP when i try to change their group or doing any changes and clicking "save" nothing happens 
its like the "save" button is not clickable for this member

**Comment by madman32395** [comment]
so when you get that EX0, the error you put in OP is what you get? 

so with the plugin enabled, you cannot edit any members? 

also you are on 4.1.4? You should update to 4.1.4.1 as there is a security patch released on that. also with the release of 4.1.4 it requires php  5.4.0 or greater, and the plugin requires cURL enabled.

**Comment by taman1990** [comment]
im already on 4.1.4.1 
and i was wrong looks like members at spam, locked, banned, normal members too 
i tried a couple of them in each group same issues 
at acp when i click save on this groups this error shows up at browser console
An invalid form control with name='core_pfield_12' is not focusable.

**Comment by taman1990** [comment]
could it be the members who used steam profile sync ?

**Comment by madman32395** [comment]
i doubt it, steam writes to the member table instead of the profile fields area.  IPS is quick to blame other apps.

But is your server config compatible with IPS 4.1.4 and higher?

**Comment by taman1990** [comment]
im on php 5.4.43

**Comment by madman32395** [comment]
I would recommend making sure your server config matches IPS base requirements. As that can cause crazy things to happen to the core software.

**Comment by taman1990** [comment]
no sir its not the server configuration error! its the steam login issue and my website is fine from everything it was also fine before i update the core

**Comment by taman1990** [comment]
the core says its completable its not a bit possible to be the serve configuration error

**Comment by taman1990** [comment]
what server configuration error exactly ?

**Comment by madman32395** [comment]
with the steam enabled, have you trying modifying any user accounts or anything on a default (unmodded) theme?

**Comment by taman1990** [comment]
yes i have tried almost everything on my own until i was out of hopes and created a ticket for the SHIT support at ips which took 7 days to answer and telling me that the problem is the steam login plugin

**Comment by madman32395** [comment]
hmm. if youre cool with it, I could take a peak? im on steam currently. steamcommunity.com/id/madman32395

**Comment by taman1990** [comment]
im at work on another pc and i dont have steam installed here 
maybe skype?

**Comment by madman32395** [comment]
sure, same username.

**Comment by taman1990** [comment]
alright :)

**Comment by Lavoaster** [comment]
Has anything come of this? Is it still an issue?

**Comment by taman1990** [comment]
nope still same i only fixed the members who is active and they login others are completely fucked up

**Comment by madman32395** [comment]
:/ you shouldnt need to create accounts and merge them. sounds like they just have moderation flags on their accounts for some odd reason.

**Comment by taman1990** [comment]
what moderation? if you mean there a fix please tell me there is still hundreds of broken members

**Comment by madman32395** [comment]
@taman1990 for your forums, did you upgrade to 4.x from a previous version? such as 3.4.8 to 4.x?

**Comment by taman1990** [comment]
yes i did

**Comment by madman32395** [comment]
did you repurpose the old banned group?

**Comment by taman1990** [comment]
no sorry not from 3.4.8 it was 3.4.7 then i upgraded to 4.x

**Comment by taman1990** [comment]
no i didnt do anything i just upgraded to 4.x back then

**Comment by madman32395** [comment]
ah, so the default banned group has always been banned group?

**Comment by taman1990** [comment]
yes probably and i didnt care since i only have 2 -5 users banned

**Comment by madman32395** [comment]
ok, my theory was then incorrect then. was thinking you renamed the group and was using it as something else... but from what I understand, there is nothing in the steam logon handler that controls ban/moderation permissions. So something else happened. Potentially another app outside of this one that messed up your member table.

As for proper installation of the plugin, I could help you verify that its installed.

**Comment by taman1990** [comment]
no i never renamed my banned group 
but with a ticket from ips support they say its steam login problem and they show the error logs as u see in my first post here :/

**Comment by madman32395** [comment]
Do you currently still have these errors reoccuring? Because those wouldnt do anything to your members directly, the only thing the login handler does is add a steamid to the member table.

**Comment by taman1990** [comment]
mmm i don't know where exactly to check this errors :/

**Comment by madman32395** [comment]
I see that earlier you added me on skype. Ill ask for more sensitive information there.

**Comment by taman1990** [comment]
alright im at work riht now i cant use skype for now
but one more question 
in acp when i try to change their account info and clicking on "Save" this error shows up on browser console 
" An invalid form control with name='core_pfield_12' is not focusable.  "  
is this core_pfield_12 has anything to do with the steam app?

**Comment by madman32395** [comment]
nope.

**Comment by taman1990** [comment]
and do you have any idea what core_field stands for?
is it profile fields by any chance?

**Comment by madman32395** [comment]
Profile Fields... like where you type in Location, Sex, social contact information (such as skype, icq, etc.)

**Comment by taman1990** [comment]
so the problem must be with one of the profile fields what u think?

**Comment by madman32395** [comment]
with pfields yes. unrelated to steam login. as the steam login just adds a column directly to the _core_members table.

That would be one of possible many issues. What I would recommend is reuploading the client suite, and running the support tool under System>Support , and check something is wrong and run that all the way through; but do NOT file the support ticket at the end; just go through the automated support process.

**Comment by taman1990** [comment]
i have already re uploaded the suite to refresh the files once only and it didnt help
i dont want to use "something is not working " tool since one time i used it and fucked up my forum with an error says configuration error and blabla went alot to fix im afraid if same shit happens

**Comment by madman32395** [comment]
if doing the support tool breaks your forums, there's something deeper than what IPS is trying to tell you.

**Comment by taman1990** [comment]
what you mean ?

**Comment by madman32395** [comment]
I mean its a whole lot deeper than ips blaming the steam login. the support tool is supposed to find broken stuff, instead its finding errors, but is unable to complete its repair.

if you are able to, I would take a backup, and on a test site perform the update, and then the support tool and see if it breaks again, if the test site breaks. grab the errors and bring it up to IPS. 

I've ran the support tool on just about every community I have done support on, and haven't seen bigger issues arise.

**Comment by taman1990** [comment]
will do another day but im sure it wont fix shit xD
