### ISSUE TITLE
Installed ok/API key ok/not working

### ISSUE THREAD

**Issue by gabrielt** [Lavoaster/IP.Board-Steam-Authentication-Method#42]
Installed ok. Configured API ok. Steam buttons show up on login/registration/account settings. Everything looks good. Except it doesn't work.

When clicking on the black button to link my account to Steam's on the settings page, the Steam login screen shows up, but after accepting we are redirected to our website, and nothing happens.

When tryng to create a new account using the Steam button, it simply says an error has occurred.

I don't even know how to debug this.

**Comment by Lavoaster** [comment]
Is the login handler enabled?

**Comment by gabrielt** [comment]
Of
![cdh-steam1](https://cloud.githubusercontent.com/assets/5942846/11794150/fa1b4170-a303-11e5-8fde-04ef79030e93.png)
![cdh-steam2](https://cloud.githubusercontent.com/assets/5942846/11794152/fa46e00a-a303-11e5-9fb9-bb0317e16812.png)
![cdh-steam3](https://cloud.githubusercontent.com/assets/5942846/11794151/fa43e1a2-a303-11e5-86be-6482cf030f58.png)


 course...

**Comment by madman32395** [comment]
@gabrielt I would recommend either censoring your api key or removing that picture. Security and such lol...

got a free moment, I could take a look if you want?
http://steamcommunity.com/id/madman32395

**Comment by gabrielt** [comment]
@madman32395 got it, thanks.

**Comment by madman32395** [comment]
@gabrielt im free currently if you would like another set of eyes looking at it. Hit me up on steam if you want.

**Comment by gabrielt** [comment]
@madman32395 try creating an account at forum.clubedohardware.com.br using Steam...

**Comment by madman32395** [comment]
yea, i get the 'Something went wrong. Please try again' error.

**Comment by madman32395** [comment]
@gabrielt that error doesnt tell anyone on the public side what is going on, so I have no clue without seeing the backend.

**Comment by gabrielt** [comment]
That is why I need help... I have no clue what is going on... The logs don't show anything... I don't even know where to start...

**Comment by madman32395** [comment]
welp, send me a message on steam. im heading to bed at the moment, but should be good to go in a few hours to get you up and running

**Comment by gabrielt** [comment]
Hi, added you as my friend there. You can also reach me here:
http://www.clubedohardware.com.br/pagina/contato
Thank you for your help!

**Comment by madman32395** [comment]
Cool. Let me grab my computer. I accepted your friend request.

**Comment by madman32395** [comment]
@gabrielt iight, im all setup. added you on steam, ready to play.

**Comment by gabrielt** [comment]
Thanks, I am with the chat window open so we can fix this issue together.

**Comment by madman32395** [comment]
After troubleshooting, it was found that rewrite urls on his ngnix configuration was the issue, after rewrite was disabled, steam login started working fine. 

He is looking into his configuration as to why it failed.

#notasteamloginissue.
