### ISSUE TITLE
Problem installing with new update

### ISSUE THREAD

**Issue by shadowtor** [Lavoaster/IP.Board-Steam-Authentication-Method#43]
So just installed and updated fresh to new version of IPB4
seems that it wont even install the plugin at all, it pretty much just crashes..
is doing this with around 50% of plugins atm.
Any reason behind this?
Any fix to get them working?

**Comment by Lavoaster** [comment]
Sounds like an IPB issue, not this plugin.

**Comment by shadowtor** [comment]
Spoke to them before posting this and they said the same thing but for the plugin<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: Adam Lavin <notifications@github.com> </div><div>Date: 18/12/2015  1:46 am  (GMT+10:00) </div><div>To: "Lavoaster/IP.Board-Steam-Authentication-Method" <IP.Board-Steam-Authentication-Method@noreply.github.com> </div><div>Cc: Tom <shadowtor@live.com> </div><div>Subject: Re: [IP.Board-Steam-Authentication-Method] Problem installing with new update (#43) </div><div>
</div>
Sounds like an IPB issue, not this plugin.

---

**Comment by madman32395** [comment]
Give me 20 minutes to clean myself up.... Add me on steam and I could take
a peak.
Www.steamcommunity. com/id/madman32395

**Comment by madman32395** [comment]
@shadowtor iight, if ya want, im ready to see what broke.

**Comment by madman32395** [comment]
taking the user setup error off, as the test install and production site are both 100% fresh installs.

**Comment by madman32395** [comment]
User trying to get in contact with host; meets/exceeds all requirements for IPS Core.  Both live and test installs have issues. Determined to be host/server config.
