### ISSUE TITLE
Wont allow signup or sign in just redirects

### ISSUE THREAD

**Issue by jacrealms** [Lavoaster/IP.Board-Steam-Authentication-Method#44]
Click sign in with steam you got to steam and login with your creds then it just goes back to the previous screen without logging you in and or signing them up.

**Comment by madman32395** [comment]
Did you upload the files correctly? Plugin and login handler enabled? Curl
enabled?

**Comment by jacrealms** [comment]
Ya I uploaded the files in the upload folder and I have CurlSSL installed as well as have the plugin and login handler enabled

**Comment by madman32395** [comment]
How about rewrite URL? Is this enabled and setup correctly?

**Comment by jacrealms** [comment]
Where could I look that up?

**Comment by jacrealms** [comment]
https://gyazo.com/ad767f798ce2a4ceaaf7778dfe6b2060

**Comment by madman32395** [comment]
Hmm. Just want to make sure. When you run the system check under support.
Everything is good?

**Comment by jacrealms** [comment]
yup

**Comment by madman32395** [comment]
Interesting. If you would like. I could take a peak? Add me on steam.
Steamcommunity.com/id/madman32395

**Comment by jacrealms** [comment]
Added

**Comment by Fighting13th** [comment]
I am having the same issue.  I have IPB Hosted through IPB.  I installed everything correctly. Only step I am not sure of is Enabling Curl.  When you go to Steam and sign in, it looks like it's redirecting but then it goes to a blank screen.  If you hit refresh it takes you to the "Finish Profile" where you enter your display name and email etc.  But none of the Profile syncing works.

**Comment by madman32395** [comment]
@Fighting13th Could you add me on steam, I have spoken to multiple admins/managers on your community. And none of them know who made this comment.

**Comment by madman32395** [comment]
@Fighting13th With no reply after 10 days, I have removed your comment on this issue report. If you have further issue please open a separate issue report.

**Comment by madman32395** [comment]
@jacrealms I visited your site the other day, everything seemed to be working fine. Did something change? Did you guys get it working?

**Comment by madman32395** [comment]
Lost contact with jacrealms. Attempted Teamspeak and other community administrators. Assuming fixed as site login works.
