### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by eth007** [Lavoaster/IP.Board-Steam-Authentication-Method#45]
We updated from ips3 with the steam login plugin now we are on ip4.1 with the ip4 version of steam login but every time i try and login with steam id it takes me back to the login screen i have tried re-linking my account with steam but it didn't make a difference. i have all so made sure i added the api key

Any help would be appreciated, Thank you
our website: phantom-gamers.net
Steam: http://steamcommunity.com/id/Killer_Awesome_Phantom/

**Comment by madman32395** [comment]
@eth007 Sent steam request.

**Comment by madman32395** [comment]
Met with Eth007; after looking at setup, verified setup was done correctly. Even updated to pre-release 2.0.1 still had issues. Spun up a test ips install, found the test install worked flawlessly. Found a difference setup wise. SSL. Disabled SSL for login on live site, and steam registration, login, link and unlink worked flawlessly. Something serverside with the SSL seems to be causing the issue.
