### ISSUE TITLE
steam login doesn't work with URL rewriting turned on

### ISSUE THREAD

**Issue by GeorgeRiley** [Lavoaster/IP.Board-Steam-Authentication-Method#46]
On our site (unloze.com) (IPB4) the steam login does not work with URL rewriting turned on, is this related to using nginx to rewrite the URLS,

or is it due to the plugin itself.

All I have to do to reproduce it is turn on url rewriting in IPB with my nginx try_files directive (which handles IPB's FURL rewriting nicely):

content of the appropriate location blocks in the nginx config for the site:
```
        location /forums {
                try_files $uri $uri/ /forums/index.php;
        }

        location ~^/forums/(/page/).*(.php)$ {
                try_files  $uri $uri/ /forums/index.php;
        }
```

If there is a way to fix this through changing our nginx configuration or by fixing the plugin it would be highly appreciated :).

(right now url rewriting is off to alleviate this)

EXTRA EDIT: turning url rewriting on but force friendly urls on also fixes this.

**Comment by madman32395** [comment]
Try 

   location / {
        index       index.html index.php;
        try_files $uri $uri/ /index.php?q=$request_uri;
    }

**Comment by GeorgeRiley** [comment]
Doesn't rewrite properly, cant access "Account Settings" but most of the forum is accessible.

So unable to test that configuration unfortunately.

Perhaps the way the plugin reads the data passed from steam is just not compatible with nginx rewriting no matter how you do it.

**Comment by madman32395** [comment]
It's odd because I've seen the plugin work on ngnix with rewrite.

**Comment by GeorgeRiley** [comment]
It only works if force friendly urls is off with the current rewrite configuration i posted.

**Comment by madman32395** [comment]
That would still be a server configuration issue; outside of the plugin.
