### ISSUE TITLE
Complete Registration page blank

### ISSUE THREAD

**Issue by slapglif** [Lavoaster/IP.Board-Steam-Authentication-Method#47]
when any user tries to register with steam, they are able to proceed to the point where they enter their email, click continue, and they get the following:

http://i.imgur.com/vHyDzoP.png

source: [removed]

ive confirmed that the div is not set to display none and checked the registration.php - not sure whats up

**Comment by madman32395** [comment]
>Accepted Steam buddy request ; suggested to try a default unmodified theme as it appeared that it was not loading JS after asking what email you wanted to use.

**Comment by Lavoaster** [comment]
@slapglif Could you use an alternative host for the screenshot than puush, like imgur? Puush is great for IM conversations but at some point in the future it will automatically purge your screenshot which will ruin the history for this issue should we need to review it in the future.

**Comment by slapglif** [comment]
updated image url and removed source for privacy, i tried another template, still no dice.

**Comment by Lavoaster** [comment]
Does this work on the default theme?

**Comment by slapglif** [comment]
it does not, thats what i tried.

**Comment by madman32395** [comment]
I installed a local WAMP stack on my computer, with 3.4.9 and the steam login for 3.x from github, and was able to register just fine (like completely logged out, and followed reproduction steps). seems to be an issue locally on their end. 

@slapglif  random question, have you tried doing a fresh install of 3.4.9?
