### ISSUE TITLE
IPS Cloud system

### ISSUE THREAD

**Issue by Soloknight** [Lavoaster/IP.Board-Steam-Authentication-Method#48]
I have tried to get this installed, but it doesn't show up in the Login Handlers. It installs just fine with no errors latest board ver.

**Comment by Lavoaster** [comment]
Can you ensure that you've uploaded all the files and correctly installed the hook.

**Comment by madman32395** [comment]
@Soloknight Are you still having issues? If you would like I could take a look for you.

**Comment by Soloknight** [comment]
It's all good, got it working, we had a problem with ftp access. Thanks for
the plugin works great.
