### ISSUE TITLE
Double Post

### ISSUE THREAD

**Issue by Skamadix** [Lavoaster/IP.Board-Steam-Authentication-Method#49]
Users that sign in through steam all double post each time they make a post on the forum.

Each time they post, they are prompted with
Sorry, there is a problem
Something went wrong. Please try again.
Error code: EX0

This error then generates the below in the error logs in the ACP
OutOfRangeException
0: 
#0 /home/carbon/public_html/system/Content/Item.php(3334): IPS\Patterns\_ActiveRecord::load(0)
#1 /home/carbon/public_html/system/Content/Item.php(3151): IPS\Content\_Item->processCommentForm(Array)
#2 /home/carbon/public_html/system/Theme/Theme.php(694) : eval()'d code(3129): IPS\Content\_Item->commentForm()
#3 [internal function]: IPS\Theme\class_forums_front_topics->topic(Object(IPS\forums\Topic), Array, NULL, Array, Object(IPS\forums\Topic), NULL, Array)
#4 /home/carbon/public_html/system/Theme/SandboxedTemplate.php(57): call_user_func_array(Array, Array)
#5 /home/carbon/public_html/applications/forums/modules/front/forums/topic.php(267): IPS\Theme\_SandboxedTemplate->__call('topic', Array)
#6 /home/carbon/public_html/applications/forums/modules/front/forums/topic.php(267): IPS\Theme\SandboxedTemplate->topic(Object(IPS\forums\Topic), Array, NULL, Array, Object(IPS\forums\Topic), NULL, Array)
#7 /home/carbon/public_html/system/Dispatcher/Controller.php(94): IPS\forums\modules\front\forums\_topic->manage()
#8 /home/carbon/public_html/system/Content/Controller.php(46): IPS\Dispatcher\_Controller->execute()
#9 /home/carbon/public_html/applications/forums/modules/front/forums/topic.php(40): IPS\Content\_Controller->execute()
#10 /home/carbon/public_html/system/Dispatcher/Dispatcher.php(129): IPS\forums\modules\front\forums\_topic->execute()
#11 /home/carbon/public_html/index.php(13): IPS\_Dispatcher->run()
#12 {main}

**Comment by madman32395** [comment]
This wouldnt be a fault of the plugin.

If you want I could look into it anyway. hit me up on steam.

**Comment by Skamadix** [comment]
What is your steam?

**Comment by madman32395** [comment]
http://steamcommunity/id/madman32395

**Comment by Skamadix** [comment]
Added, thanks
