### ISSUE TITLE
Call to undefined method IPS\Login\Steam::canProcess()

### ISSUE THREAD

**Issue by stormdr1ve** [Lavoaster/IP.Board-Steam-Authentication-Method#50]
When a user tries to dissociate from a different login method, each login handler's `canProcess` method is called (in `\IPS\core\modules\front\system\settings`) to check whether the user has any other login handlers associated with their account. Your login handler doesn't have this method, causing an exception.
I have also filed a bug with IPS: https://community.invisionpower.com/4bugtrack/active-reports/loginabstract-is-missing-required-method-canprocess-r10437/

**Comment by madman32395** [comment]
What is your site? I'll check it out in about an hour.

**Comment by stormdr1ve** [comment]
https://linustechtips.com/main/, but the issue should be present on all sites.

**Comment by Lavoaster** [comment]
@stormdr1ve This sounds like it should be a fatal error, however, it doesn't appear to be. I logged into the linus site with my steam account, linked my google account and then unlinked the steam account without any errors.

Is this error only appearing in the logs?

**Comment by stormdr1ve** [comment]
@Lavoaster You have to dissociate a different method, and you also need to either only have Steam and that other method enabled initially, or the only other methods that are enabled need to be after Steam in the login handlers list (on that site, none are, so you need to just have steam and something else (eg Google) enabled, then disable that other handler (Google)).

**Comment by Lavoaster** [comment]
What version of IP.Board did `canProcess` get implemented in?

**Comment by stormdr1ve** [comment]
I'm not sure (I would have guessed that it was there from the start, but I don't have any of the old files), but adding it shouldn't break any older installations unless IPS did something really strange.

**Comment by madman32395** [comment]
I tried to disassociate my account from a GTA RP website that I used steam
as my only login and it told me I couldn't disassociate my steam since it
was the only way of logging into my account. I'll try on your site here in
a sec.

**Comment by Lavoaster** [comment]
@madman32395 The bug is attempting to disassociate another login handler whilst the steam one is associated.

**Comment by Lavoaster** [comment]
@stormdr1ve I appreciate this bug report, I have no idea how this was missed previously. Anyway you will find the updated version on the marketplace or in the releases here on github.

This plugin almost went a year without bugs, I guess the clock resets now... :smile:
