### ISSUE TITLE
not working 4.1.10

### ISSUE THREAD

**Issue by techpulse** [Lavoaster/IP.Board-Steam-Authentication-Method#53]
corrupted my site, ips staff said..

"No, that is a different issue caused by the Steam login handler. It is currently incompatible with the latest version, so I recommend contacting the author to see if there is an updated version available.

**Comment by madman32395** [comment]
Have you updated your steam plugin to 2.0.2?

**Comment by madman32395** [comment]
Reason why I ask, is my live site, and various other communities that I manage currently do not have any issue.

**Comment by madman32395** [comment]
my bad, i misread that and thought you meant 4.1.9 ' ill be installing a run of 4.1.10 right now, and seeing whats up

**Comment by cammackmatthew** [comment]
So we're also having the same issue with the latest IPBoard update.

`Fatal error: Class IPS\Login\_Steam contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (IPS\Login\_LoginAbstract::canProcess) in C:\inetpub\wwwroot\forums\system\Login\Steam.php on line 277`

We're using 2.0.2 and issue is happening.

**Comment by Drehmini** [comment]
We're using 4.1.10 and we're receiving this error.
We receive a 500 error along with the below. Disabling/uninstalling the plugin has no affect.


```
Fatal error: Class IPS\Login\_Steam contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (IPS\Login\_LoginAbstract::canProcess) in /home/validusgamers/public_html/system/Login/Steam.php on line 0
```

**Comment by madman32395** [comment]
@techpulse @Drehmini I suggest updating steam to 2.0.2 


@cammackmatthew since you say youre on 2.0.2 and still having issue. i would like a closer look in your acp and would need ftp. add me on steam for private messaging. http://steamcommunity..com/id/madman32395

**Comment by cammackmatthew** [comment]
@madman32395 I've sent a request.

**Comment by Drehmini** [comment]
@madman32395 We are at version 2.0.2 (20002) See attached.
![steamver](https://cloud.githubusercontent.com/assets/3511956/14359511/b39d949e-fcbf-11e5-9c08-1dce30fdb03d.PNG)

**Comment by madman32395** [comment]
@Drehmini hmm. looks like you get to add me as well.

**Comment by madman32395** [comment]
K matthew is back up and running. @Drehmini You ready?

**Comment by Drehmini** [comment]
@madman32395  I'm currently at work. I'll have one of my administrators contact you shortly.

**Comment by madman32395** [comment]
sounds good :+1:

**Comment by madman32395** [comment]
k drehmini is up and running again. @techpulse you still having issues?

**Comment by Lavoaster** [comment]
@madman32395 What's the issue?

**Comment by madman32395** [comment]
@Lavoaster Unknown issue with techpulse, but the other two were just simple update of the plugin (both xml AND upload folder; appeared to have only updated the xml)

**Comment by AustinARPL** [comment]
I had the same issue, all it takes to fix is to manually upload all of the files in the uploads folder to your server and then it should work on a refresh

**Comment by madman32395** [comment]
Yup. That's how you update it. Upload the upload contents, and update
plugin using the XML. :)

**Comment by madman32395** [comment]
@techpulse I have no heard back from you in over 9 days, if you still have this issue please update your app by uploading the upload folder contents, and clicking upload new version on your plugin then upload the xml.

if you continue to have this issue afterwards or require assistance updating, please feel  free to get in contact with me or reopen this issue.

Thanks - Closing Issue.

**Comment by techpulse** [comment]
Sorry, forgot about it. Will try now.

**Comment by ADKGamers** [comment]
So we upgraded last weekend to 4.X (latest version) and are having the issue where it redirects. I've uploaded the files numerous times from multiple computers just to make sure it wasn't something funky on one computer and also updated the plugin again, but still running across this issue. Let us know what you need from us to help troubleshoot.

Thanks

**Comment by madman32395** [comment]
I'm sorry you are having issues. I work until 10pm CT , I could poke around
then and see what's happening?

**Comment by ADKGamers** [comment]
Any help would be great. :)

**Comment by ADKGamers** [comment]
@madman32395 let me know the best way to get in touch with you.

**Comment by madman32395** [comment]
@ADKGamers best way to get in touch with me is on steam www.steamcommuntiy.com/id/madman32395 ; or skype madman32395

**Comment by ADKGamers** [comment]
@madman32395 sent the request on steam
