### ISSUE TITLE
Check Username Restrictions

### ISSUE THREAD

**Issue by ADKGamers** [Lavoaster/IP.Board-Steam-Authentication-Method#54]
Hello,

I know that it pulls the name directly from steam but was wondering if there's anyway to either follow the username restrictions that are in place on the forums, or make it sot hat people have to enter in usernames. 

The reason for this request is there's a lot of people who have special characters in their names, especially at the beginning and it makes it difficult to tag them on the forums. 

So if something could be implimented to fix this, that'd be awesome. 

Thanks!

**Comment by madman32395** [comment]
@ADKGamers If you wish to not have the system use steam usernames and have your users manually type their username just turn off this setting in the login handler 'Use Steam Username?'
https://drive.google.com/file/d/0B0mBb9QuGv84QTJzNHpwVkpxMG8/view?usp=drivesdk

New registrations will ask the user then to enter a username.

**Comment by ADKGamers** [comment]
@madman32395 sorry -_-  Been trying to fix a bunch of bugs with the IPB devs, not much sleep and totally forgot about that.  My bad. . haha
