### ISSUE TITLE
Not going to upgrade to IPB4, but have ssl Problem.

### ISSUE THREAD

**Issue by Napsterlove** [Lavoaster/IP.Board-Steam-Authentication-Method#55]
Before you ask lol, I will not be upgrading to IPB4 (probably would fix all my problems), as I paid a designer for a custom theme some time ago, and don't see it as a wise decision atm.

Anyways, My problem is the result of changing the entire site to HTTPS via a cloudflare proxy. The site itself works flawlessly, however my login methods are troublesome. Steam Authentication works normally, until after a user signs into steam, upon the 'sign in' (after entering credentials) the page loads, and doesn't move forward. It's almost as if it isn't connecting to the board. (started after changing to ssl)

Any suggestions? / easy fixes?

Currently running 1.1.2, with IPB 3.4.6 & Cloudflare: flexible ssl (always use https page rule)

**Comment by madman32395** [comment]
Is it keeping the user on the steam login page?

Also would still suggest 4.x as that is what IPS is now fully supporting
and they only do security patches for 3.x.

**Comment by Napsterlove** [comment]
Yes, It loads briefly, and keeps the user on the steam login page, instead of redirecting to the board. I would rather live without steam login than upgrade at this point lol.

**Comment by madman32395** [comment]
I have a feeling on what it is. But I'm not home atm.

**Comment by madman32395** [comment]
@Napsterlove sup bud, hit me up on steam ; would need FTP and ACP.  http://steamcommunity.com/id/madman32395

**Comment by Napsterlove** [comment]
Sent an invite, awaiting acceptance

**Comment by madman32395** [comment]
Found client setup issue, forgot to turn on SSL with login, as rest of site is https. this was causing openID to freak out as it came from a https site but wanted to return to a http site. openid wasnt having none of that. Ticked on Login with SSL. but then further server issues appeared. @Napsterlove would have to correct redirect loop issue on their server first. Might be a Cloudflare issue. Suggested using Lets Encrypt as a replacement for their SSL certs.
