### ISSUE TITLE
Not work in 4.1.13 - canProcess()

### ISSUE THREAD

**Issue by hznovich** [Lavoaster/IP.Board-Steam-Authentication-Method#56]
PHP Fatal error:  Class IPS\\Login\\_Steam contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (IPS\\Login\\_LoginAbstract::canProcess) in /home/..../system/Login/Steam.php on line 0, referer: https://..../admin/?adsess=oj445uje4fvpr3k0v1buih9je5&app=core&module=system&controller=login&error=NO_ADSESS&ref=

**Comment by madman32395** [comment]
have you updated this plugin to 2.0.2 and reuploaded the upload folder contents? I can validate that it works in 4.1.13

**Comment by madman32395** [comment]
@hznovich are you still having issues?

**Comment by hznovich** [comment]
Sorry man. Yet to be tested, not enough time. Closer to the weekend check and write the result.

**Comment by hznovich** [comment]
Worked. Sorry for long answer. The problem was due to another plugin. But in the logs was a mention of steam login.

**Comment by madman32395** [comment]
@hznovich no prob, figured the CanProcess and having issues thought you were a recent updater and didn't update the steam plugin fully or at all :+1:
