### ISSUE TITLE
Save users to external database?

### ISSUE THREAD

**Issue by gerrard9099** [Lavoaster/IP.Board-Steam-Authentication-Method#57]
Is it possible to save users to another database? I will run a sql script to check for Steam id's and the cloud hosting does not support those kinds.

Pasting some raw code here.
`reguservoiceenabler_query   "SELECT * FROM `ipbmembers` WHERE `steamid` = '{steamid}';"
reguservoiceenabler_steamidformat 1`

Thanks again.

**Comment by madman32395** [comment]
this writes steamid's to the core_member table.  why not have your script target the core_member table to get the 'steamid' column?

tldr; no its not possible for this plugin to write to external.
