### ISSUE TITLE
profilesync task locks up with this plugin

### ISSUE THREAD

**Issue by PresidentEvil** [Lavoaster/IP.Board-Steam-Authentication-Method#59]
I'm using IPS 4.1.14.3

Members am unable to upload or change photos, IPS support says this plugin is causing the issue. When I disable this plugin, this error goes away and profilesync runs fine.

InvalidArgumentException:  (0)
#0 /home/slayersg/public_html/system/Image/Image.php(95): IPS\Image\_GD->__construct(Object(IPS\Http\Response))
#1 /home/slayersg/public_html/system/File/File.php(217): IPS\_Image::create(Object(IPS\Http\Response))
#2 /home/slayersg/public_html/system/Http/Url.php(575): IPS\_File::create('core_Profile', '2c3b1b4abe4bf23...', Object(IPS\Http\Response))
#3 /home/slayersg/public_html/applications/core/sources/ProfileSync/**Steam.php**(75): IPS\Http\_Url->import('core_Profile')
#4 /home/slayersg/public_html/applications/core/sources/ProfileSync/ProfileSyncAbstract.php(238): IPS\core\ProfileSync\_**Steam->photo()**
#5 /home/slayersg/public_html/applications/core/tasks/profilesync.php(41): IPS\core\ProfileSync\_ProfileSyncAbstract->sync()
#6 /home/slayersg/public_html/system/Task/Task.php(245): IPS\core\tasks\_profilesync->execute()
#7 /home/slayersg/public_html/applications/core/modules/admin/settings/advanced.php(519): IPS\_Task->run()
#8 [internal function]: IPS\core\modules\admin\settings\_advanced->runTask()
#9 /home/slayersg/public_html/system/Dispatcher/Controller.php(85): call_user_func(Array)
#10 /home/slayersg/public_html/applications/core/modules/admin/settings/advanced.php(35): IPS\Dispatcher\_Controller->execute()
#11 /home/slayersg/public_html/system/Dispatcher/Dispatcher.php(129): IPS\core\modules\admin\settings\_advanced->execute()
#12 /home/slayersg/public_html/6921/index.php(13): IPS\_Dispatcher->run()
#13 {main}

**Comment by madman32395** [comment]
Do you have cURL enabled and to recommended or higher version?

**Comment by madman32395** [comment]
* or have ImageGD enabled / installed correctly?   ; while the error says its steam, this is not an issue for myself or the many others that have it installed.

**Comment by PresidentEvil** [comment]
my bad, it was a server issue, all fixed now
