### ISSUE TITLE
Forum version 4.1.15

### ISSUE THREAD

**Issue by ChicagoMikey** [Lavoaster/IP.Board-Steam-Authentication-Method#61]
Plugin may not work on forum version 4.1.15. User tried to sign into forum via plugin and received error: Not Acceptable

**Comment by madman32395** [comment]
> received error: Not Acceptable

Can you provide a screenshot or logs of some kind. I have never seen that error with this plugin or natively in IPS related to login.

One thing I would check for is proper rewrite, and make sure you have the login fully setup (API key, upload folder uploaded correctly, using latest Steam Login, plugin enabled)

**Comment by ChicagoMikey** [comment]
This plugin worked before I upgraded. Just to make sure, I reinstalled the plugin before recording the below video: https://youtu.be/ms-oW8lGjNE

**Comment by Lavoaster** [comment]
Can you post your nginx vhost?

**Comment by Lavoaster** [comment]
Actually, you're using Litespeed and on review, I don't see any part of this plugin that would ever issue a `406 Not Acceptable` request back. Add that to the fact that only 'Not Acceptable' is in the body of the response leads me to believe you've got a misconfigured server.

I won't be able to help you with this, something on your web server must have changed at the same time as your upgrade.

**Comment by ChicagoMikey** [comment]
Ok, so I discussed the issue with my host and you guys were right, hopefully the below information will help out other users having the same issue as me:

A 'Not Acceptable' error usually means you're triggering a mod_security rule we have in place. Considering this is doing an authentication through a third party URL/resource I wouldn't be surprised that were the case. Please add the following to your forum installation directories .htaccess file and then try to replicate this again:

<IfModule mod_security.c>
SecFilterEngine Off
SecFilterScanPOST Off
</IfModule>

**Comment by Lavoaster** [comment]
🎉
