### ISSUE TITLE
cloud hosted version 4.1.15 issue with "login Handler"

### ISSUE THREAD

**Issue by VahaknN** [Lavoaster/IP.Board-Steam-Authentication-Method#62]
Hi there Lavoaster
  Am currently testing out your plugin on a temporary trial version of the Ipboard in a cloud host environment. version 4.1.15. i uploaded the steam xml file as you instructed, made sure it is enabled from the "plugins" menu, but when i navigate to the "login handler" section it does not show the "Steam" option at all as your instructions say. its not present with the rest of the options. What could i be doing wrong?

PS: am a noob at this.

all the best

V.
![steam1](https://cloud.githubusercontent.com/assets/22812322/19343830/8c8e4b58-9140-11e6-988d-548550d6f9b4.jpg)
![steam2](https://cloud.githubusercontent.com/assets/22812322/19343831/8caa29ae-9140-11e6-9459-793c64790fc8.jpg)

**Comment by madman32395** [comment]
The plugin also needs files to be uploaded. The "Test/Demo/Trial" version
is very restricted anyway.

But it is possible to install onto a CiC (Cloud) installation. IIRC we have
a few clients on CiC.
