### ISSUE TITLE
ACP login problem IPS 4.1.16.1

### ISSUE THREAD

**Issue by kyllagdrgn** [Lavoaster/IP.Board-Steam-Authentication-Method#63]
After updating to IPS 4.1.16.1 my admin users using Steam auth can no longer get to the ACP. The login process seems to go well until it returns to IPS where you are presented with the error "Something went wrong. Please try again." on the login pane.

**Comment by madman32395** [comment]
Please update your plugin against the GitHub. ACP was updated on GitHub pending release to IPS Marketplace.

If after updating issue is still there let me know.

**Comment by madman32395** [comment]
Please update your plugin against the GitHub. ACP was updated on GitHub
pending release to IPS Marketplace.

If after updating issue is still there let me know.

**Comment by madman32395** [comment]
@kyllagdrgn are you still having issues?

**Comment by kyllagdrgn** [comment]
Thanks, I have not had time to apply the patch yet. I am sorry I did not responding earlier.

**Comment by madman32395** [comment]
That's alright. Was just checking. I don't like seeing you guys upset :P

**Comment by madman32395** [comment]
@kyllagdrgn everything doing alright? Just wondering if it's safe to close this issue :P

**Comment by kyllagdrgn** [comment]
Yes, everything is fine you can close this issue. Thanks
