### ISSUE TITLE
Login Display Error.

### ISSUE THREAD

**Issue by BritishBorders** [Lavoaster/IP.Board-Steam-Authentication-Method#64]
Hello,

I have viewed the most recent thread which suggests a fix in the URL.php but to no success. It doesn't display on our login page. (Sent via IPB 15/09)

You requested that i submitted my bug here so i will do. Although steam appears on our login handlers as shown below

https://i.gyazo.com/5cdfe627353539a0a21680a9c13c4c6e.png

That being said i have reinstalled the .xml and added the files from the upload folder manually but to no success.

https://i.gyazo.com/5707595db09c85b57bd07005c745cefc.png

Please could you help resolve this for us.

Thanks

**Comment by madman32395** [comment]
Are you using a custom theme? Try restoring the default theme and viewing it that way? It could be a theme conflict.

**Comment by BritishBorders** [comment]
OK. I will check now thanks

**Comment by BritishBorders** [comment]
It appears it is a theme issue as shown on the default theme it displays

**Comment by BritishBorders** [comment]
https://i.gyazo.com/5913645af69a18d5a4c2aee8b44310f0.png

**Comment by BritishBorders** [comment]
The problem has been fixed. Thanks
