### ISSUE TITLE
New users not able to sign up

### ISSUE THREAD

**Issue by AustinARPL** [Lavoaster/IP.Board-Steam-Authentication-Method#65]
I was on 4.1.10 and users were able to sign up, but now since I updated to 4.1.16.1 new users get met with this error after signing into steam: https://i.gyazo.com/1ef32ac9ef5f0744c7055f100df45213.png

They come up as this afterwards https://gyazo.com/a616a259616c42fe0770dd78f1af16f7

**Comment by madman32395** [comment]
Check your redirects, that's a server issue.

**Comment by madman32395** [comment]
@AustinARPL  I am going to assume everything is working again for you guys. I visited ArmaRP.life and registered via steam, and provided a username and email, but was presented with an error (attempted registration at 1608 CST, 9NOV16)

> Sorry, there is a problem
You are not permitted to register a user account with this site.
Error code: 2S272/1

Safe to assume your site redirects properly and allows users to register and login?

**Comment by Lebofly** [comment]
Was probably mod_sec, I had the same issue on MyBB

**Comment by madman32395** [comment]
@AustinARPL I have not heard from you since October. Is it safe to say your issue has been resolved?
