### ISSUE TITLE
Nginx friendly URL rewrite issue

### ISSUE THREAD

**Issue by TripleThreat-FragDeluxe** [Lavoaster/IP.Board-Steam-Authentication-Method#66]
Hi,

I'm having issues getting this to work when using the friendly URLs option on nginx with the following rule:

> location` /community {
>         try_files $uri $uri/ /community/index.php;
>     }

Any help will be appreciated.

Regards,
[FragDeluxe Community](https://www.fragdeluxe.com)

**Comment by madman32395** [comment]
> Old rewrite rules:

        location / {
            try_files  $uri $uri/ /index.php;
        }
        location ~^(/page/).*(.php)$ {
            try_files  $uri $uri/ /index.php;
        }
New rewrite rules:

        location / {
            try_files $uri $uri/ /index.php?$args;
        }


That was what was provided by another plugin user.

**Comment by madman32395** [comment]
;P seems to be working fine for me

**Comment by TripleThreat-FragDeluxe** [comment]
Hi, thanks for the response but unfortunately I wasn't able to login after making the change.

I'm not too sure what's wrong, most likely something on my end if the above rule is working for you.

**Comment by Aszune** [comment]
try restart nginx after, it's necessary :)

**Comment by TripleThreat-FragDeluxe** [comment]
Hi, I did try restarting nginx and it didn't work.

I just tried again now, gave it a couple of restarts and now it's working.

Thanks for your help, this issue is now resolved.
