### ISSUE TITLE
Login to AdminCP

### ISSUE THREAD

**Issue by Lebofly** [Lavoaster/IP.Board-Steam-Authentication-Method#67]
After logging into Admin CP with steam you're sent back to the login page with "Something went wrong. Please try again." running 4.1.16.1

**Comment by Lebofly** [comment]
Looks like https://invisionpower.com/files/file/7555-sign-in-through-steam-ipb4/ is out dated

**Comment by madman32395** [comment]
Yea, the marketplace one is behind the GitHub. Have you downloaded and updated from the GitHub version?

**Comment by Lebofly** [comment]
Yeah it worked fine. Cheers
