### ISSUE TITLE
unable to sync steam account with already registered account

### ISSUE THREAD

**Issue by island55** [Lavoaster/IP.Board-Steam-Authentication-Method#68]
ipboard 4.1.16.1

under the account settings there's the Steam option, once selected and sign in through Steam's API - it brings up the exact same page as if you've never even logged in with Steam's API.

before signing in with Steam -> http://puu.sh/stkgO/39d4652c1a.png
confirming with Steam -> http://puu.sh/stkiF/173fcc0473.png
after confirming with Steam -> http://puu.sh/stkkx/6126ec1b71.png

**Comment by madman32395** [comment]
@island55 have you entered your Steam Web API key into the login handler? Have you properly uploaded the files to their correct locations? Do you use mod_sec? Custom htaccess file?

**Comment by island55** [comment]
sorry for late reply was visiting family. but yes i've entered the Steam API and auto installed the Steam plugin with the included XML file. not sure what mod_sec is but i do have an added htaccess file and when i tried to remove the htaccess file it made the forum not work anymore?

**Comment by island55** [comment]
actually i was required to use the htaccess file to have friendly URLs if i recall correctly? perhaps that's why the forum errors when the htaccess file it removed

**Comment by madman32395** [comment]
> auto installed the Steam plugin with the included XML file

Auto installed? so you installed the xml in the plugin menu... how about the files in the upload folder?

> not sure what mod_sec

Then you probably dont use it.

> i was required to use the htaccess file to have friendly URLs if i recall correctly?

Correct. Curious what Web Server are you using? Apache or NGnix?

**Comment by island55** [comment]
i did upload the contents of the upload directory in their respective directories then installed the xml file, i use nfoservers.com for my web hosting which runs Apache; https://www.nfoservers.com/webhosting.php#differences

this sign in with Steam previously worked as intended but recently stopped for some reason

**Comment by madman32395** [comment]
Have you updated via the GitHub? There were some fixes we uploaded to GitHub but have not pushed to the IPS Marketplace yet.

**Comment by island55** [comment]
i have not.. are there any special steps to upgrading? i don't want to do something incorrectly and corrupt any files

**Comment by madman32395** [comment]
no there isnt anything special for upgrading, you just download from github, then reupload the uploads folder contents and click update on the plugin (uploading the provided xml from the github download).

> use the 'upload a new version' for the sign in through Steam plugin on the ACP?

yup

**Comment by island55** [comment]
great, that seemed to have work! one more question though, is there a way i can modify the url people are directed once they complete the sign in through Steam? i'm using easy pages and when folks sign in with Steam this is what is seen: http://puu.sh/sv2Ad/1c04d05ebb.png
i'd like for them to just end up at the forum page

**Comment by madman32395** [comment]
It's just going to return them to their previously viewed page before
signing in. All the login handlers do this.

I have seen others request this on the company forums.
