### ISSUE TITLE
Sign in with Steam not showing

### ISSUE THREAD

**Issue by jujuonthatjolly** [Lavoaster/IP.Board-Steam-Authentication-Method#71]
I had followed your instructions, yet i dont have Login Methods, I have Login Handlers and Steam is not one of the handlers. It doesnt even show up. Im using v.4.1.17.1  of community suite.

please help

**Comment by madman32395** [comment]
@jujuonthatjolly sorry for the delay. Work has been busy...

do you have access to your SQL tables via PHPmyAdmin or similar?

https://github.com/Lavoaster/IP.Board-Steam-Authentication-Method/issues/32#issuecomment-149040549

I would recommend running (if confortable) the insert command to manually place the steam handler into your login methods. 

hit me up sometime if you need help running that command or further troubleshooting.

**Comment by mhknz** [comment]
I'm having this problem too, I think it;s with a recent update of IPS. Can I get help?

**Comment by madman32395** [comment]
@mhknz I've seen this issue before, it's unrelated with IPS versions as this was happening back in Late 2015.

**Comment by madman32395** [comment]
From what I see, it's not a consistent issue, and more related to the setup of server.

**Comment by mhknz** [comment]
I re-installed my Forum Board, hopefully it works now!

**Comment by madman32395** [comment]
@mhknz is this working for you?
