### ISSUE TITLE
Cant use with https/SSL

### ISSUE THREAD

**Issue by PangbornIdentity** [Lavoaster/IP.Board-Steam-Authentication-Method#72]
Hello,
We are using Microsoft single signon as well as Steam single sign on. Micosoft requires https endpoints for single sign on, this means that we have to turn on Under Login Handlers > Login Settings > Use https for logins and the AdminCP.

The issue though is this breaks single signon with steam plugin.  

Here is a dump:

Server Info:

IPS Community Suite v4.1.17.1
PHP Version	5.6.20
MySQL Version	5.5.5-10.1.20-MariaDB SQL Toolbox
Server Path	/home/systemer/public_html

Plugin Details:

Plugin Title:  Sign in through Steam
Version: 2.0.2 (20002)
author: Adam Lavin
Hooks: none

Request URL (auth steam):
https://steamcommunity.com/openid/login?openid.ns=http://specs.openid.net/auth/2.0&openid.mode=checkid_setup&openid.return_to=http://forum.systemera.net/applications/core/interface/steam/auth.php&openid.realm=http://forum.systemera.net&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.assoc_handle=front

Submit Response: 302 https://steamcommunity.com/openid/login

301 Redirect URL: 
http://forum.systemera.net/applications/core/interface/steam/auth.php?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561197976242030&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561197976242030&openid.return_to=http%3A%2F%2Fforum.systemera.net%2Fapplications%2Fcore%2Finterface%2Fsteam%2Fauth.php&openid.response_nonce=2016-12-31T16%3A33%3A48Z%2Friz03f3sZvCvnIgiDFLy68MIWA%3D&openid.assoc_handle=1234567890&openid.invalidate_handle=front&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cinvalidate_handle&openid.sig=IQM94yLanKC51Jjwf5y530y0DOg%3D

301 Redirect URL:
http://forum.systemera.net/index.php?app=core&module=system&controller=login&loginProcess=steam&openid_ns=http%253A%252F%252Fspecs.openid.net%252Fauth%252F2.0&openid_mode=id_res&openid_op_endpoint=https%253A%252F%252Fsteamcommunity.com%252Fopenid%252Flogin&openid_claimed_id=http%253A%252F%252Fsteamcommunity.com%252Fopenid%252Fid%252F76561197976242030&openid_identity=http%253A%252F%252Fsteamcommunity.com%252Fopenid%252Fid%252F76561197976242030&openid_return_to=http%253A%252F%252Fforum.systemera.net%252Fapplications%252Fcore%252Finterface%252Fsteam%252Fauth.php&openid_response_nonce=2016-12-31T16%253A33%253A48Z%252Friz03f3sZvCvnIgiDFLy68MIWA%253D&openid_assoc_handle=1234567890&openid_invalidate_handle=front&openid_signed=signed%252Cop_endpoint%252Cclaimed_id%252Cidentity%252Creturn_to%252Cresponse_nonce%252Cassoc_handle%252Cinvalidate_handle&openid_sig=IQM94yLanKC51Jjwf5y530y0DOg%253D

301 Redirect URL: 
http://forum.systemera.net/login/?loginProcess=steam&openid_ns=http://specs.openid.net/auth/2.0&openid_mode=id_res&openid_op_endpoint=https://steamcommunity.com/openid/login&openid_claimed_id=http://steamcommunity.com/openid/id/76561197976242030&openid_identity=http://steamcommunity.com/openid/id/76561197976242030&openid_return_to=http://forum.systemera.net/applications/core/interface/steam/auth.php&openid_response_nonce=2016-12-31T16:33:48Z/riz03f3sZvCvnIgiDFLy68MIWA=&openid_assoc_handle=1234567890&openid_invalidate_handle=front&openid_signed=signed,op_endpoint,claimed_id,identity,return_to,response_nonce,assoc_handle,invalidate_handle&openid_sig=IQM94yLanKC51Jjwf5y530y0DOg=

Back to Login page
Request URL:https://forum.systemera.net/login/

**Comment by madman32395** [comment]
@PangbornIdentity Hey bud, just curious was this the version found on the IPS Marketplace, or have you tried the github version? I am curious if the github's 2.0.2 will make the issues go away.

-----
Also neat looking game, I signed up to try to win a copy with Xbox Ambassadors. (waiting for the contest to end to see if I win or not lol)

**Comment by PangbornIdentity** [comment]
I think they are the same version.
judging from the lack of https redirection this was indeed a setup issue. we forced the hosted IPS site to use https everywhere and this resolved it.  Thanks for the suggestion. not sure if this is useful in a setup guide somewhere but feel free to add.

I havent worked on the title, just helped with some website stuff.  Throw a high five to any of these talented devs https://systemera.net 

Thanks again,
cheers
