### ISSUE TITLE
Log users SteamID64 In to their profile info

### ISSUE THREAD

**Issue by SlinkyDinky** [Lavoaster/IP.Board-Steam-Authentication-Method#73]
I appreciate this so much, but I'm just wondering is there a chance you can implement the users steamid64 to there profile info? This would be super efficient to me because I can easily grab their steamid64 and then whitelist them to my arma server. Thanks again.

**Comment by madman32395** [comment]
I would recommend having a plugin built on ARMA to target the forum's core_members table targeting steamid column ; since ARMA is done through steamworks have the job is done for you (just make sure to use secured servers in arma)

**Comment by SlinkyDinky** [comment]
@madman32395 That's a great idea. Sadly I don't have any coding knowledge though 👎 Will look in to it more though, thanks!
