### ISSUE TITLE
Sign in wont work

### ISSUE THREAD

**Issue by Chevy341** [Lavoaster/IP.Board-Steam-Authentication-Method#74]
I have done everything asked

- Setup API Key to Login Handlers
- Uploaded given files
- Imported .xml file to plugins
AND I get this when we go to sign up
https://gyazo.com/e53a9d91aa0e43b144bc55a5d0f26f2e
Its supposed to look like: 
https://gyazo.com/68207690032e8906bc75ccfa718d9ad0

**Comment by madman32395** [comment]
interesting. hit me up on steam. ill take a peak and see what isnt clicking. http://steamcommunity.com/id/madman32395

**Comment by Chevy341** [comment]
Added

**Comment by madman32395** [comment]
Found it was a theme issue. Ran a theme that was a close as possible to default and steam showed up again.
