### ISSUE TITLE
Login Handler Not Showing

### ISSUE THREAD

**Issue by DanielHoyland** [Lavoaster/IP.Board-Steam-Authentication-Method#76]
Hello,

I have created a free IPS Community Suite 4 forum (for trial purposes) to test how the forum works with this  plugin.

I have installed the plugin following your guide however the Steam login configuration is not showing under Login Handlers.

Have I done something wrong or is this perhaps a limitation of the trial product?

Any help would be greatly appreciated.

**Comment by madman32395** [comment]
The demo will not work with this as it requires some files to be uploaded.
Though, this is compatible with the cloud service as well as self hosted.

When using the cloud, I would recommend having IPS support download from
the GitHub to prevent issues with the marketplace version (MP is currently
out of date)
