### ISSUE TITLE
After importing account stuck on complete profile (complete registration)

### ISSUE THREAD

**Issue by fabricenl** [Lavoaster/IP.Board-Steam-Authentication-Method#77]
Website became impossible to use for newly imported accounts. Once they try to login with it the error shows up that they need to complete their profile to register even tho they already have an account. Obviously they cannot complete it as their e-mail exists in the DB.

Website = https://get-gaming.net
Contact me:

teamspeak: ts.get-gaming.net (The Fabby)

**Comment by madman32395** [comment]
![image](https://cloud.githubusercontent.com/assets/2025022/22615970/3e1b1fce-ea68-11e6-893f-378e6866c6f7.png)

This is normal, as the system doesnt have a registered steamid for the user, so signing into steam will check your DB for a steamid, no steam id recorded, it assumes its a new user. 
What the user would have to do is cancel registration, then login to their existing account and visit account settings and click steam and link it.
