### ISSUE TITLE
Accounts don't follow IPB "Remove unvalidated members"

### ISSUE THREAD

**Issue by kanalumaddela** [Lavoaster/IP.Board-Steam-Authentication-Method#78]
Basically if there's an incomplete account (user has signed in with steam, but hasn't provided a username and finished registration), it stays in the admin cp widget that shows validating members. The reason for the account requiring a username is because we have regex on usernames and the use steam name option for the login handler bypasses the regex. I just noticed there was an update today, so is that fixed?

Now for people who register with just email and password, but don't confirm their email get deleted 7 days after registering. This doesn't apply however for users who register through steam and haven't completed the registration. We have a user who registered on Feb 4th who still shows up today (the 17th) and hasn't been deleted by the forums. And of course since the registration is incomplete, I can't go through the member list or search for them using their email to delete it. The only options I have are to approve or ban it through the admincp widget. Other than that, I have to delete the user manually from the database.

A small side question for the new update is what does this mean?
> Resolves fatal error when attempting to disassociate other login methods

**Comment by madman32395** [comment]
> Basically if there's an incomplete account (user has signed in with steam, but hasn't provided a username and finished registration), it stays in the admin cp widget that shows validating members. The reason for the account requiring a username is because we have regex on usernames and the use steam name option for the login handler bypasses the regex. **I just noticed there was an update today, so is that fixed?**

-Bold (reference) ; no.

> Now for people who register with just email and password, but don't confirm their email get deleted 7 days after registering. This doesn't apply however for users who register through steam and haven't completed the registration.

-If I remember right this is a byproduct of Login Handlers except for Internal (plain old username/password)

>  Other than that, I have to delete the user manually from the database.

-Don't. Seriously don't. When a user is generated it generates in other spots in the database. The appropriate way to delete a user is through the ACP. 

> A small side question for the new update is what does this mean?
>>Resolves fatal error when attempting to disassociate other login methods

-IIRC IPS broke it, we fixed it.

**Comment by kanalumaddela** [comment]
> -If I remember right this is a byproduct of Login Handlers except for Internal (plain old username/password)

We have Google and Twitter login handlers, but since those are rarely used. I have yet to see if the same issue occurs.
> -Don't. Seriously don't. When a user is generated it generates in other spots in the database. The appropriate way to delete a user is through the ACP.

It's impossible to delete the user through ACP if they haven't completed their registration. In the ACP Dashboard widget it shows their email, ip they registered on, and when they registered. The only 2 options are Approve & Ban. Searching through the member list using their email doesn't pull their account either. I haven't deleted the user yet, but that information is good to know. Do you know what other tables a user's data is stored in?

**Comment by madman32395** [comment]
> It's impossible to delete the user through ACP if they haven't completed their registration. In the ACP Dashboard widget it shows their email, ip they registered on, and when they registered. The only 2 options are Approve & Ban. **(1.)Searching through the member list using their email doesn't pull their account either.** I haven't deleted the user yet, but that information is good to know. **(2.)Do you know what other tables a user's data is stored in?**

-1. That is because if they didn't finish registration they will not have an email. They will have a username though, and that is searchable via ACP. **But IIRC they _were_ supposed to allow showing all users regardless if they have an email listed or not. Seriously it's the email that's preventing the members module showing all users.** On my personal community I have at least 5 users that have no email at all, either due to semi-registered or fake/bounceback email. and another community I do support for has about 4 users without emails. It's just nature of 3rd party login handlers. I am sure if steam allowed us to grab emails (which they never will), we could possibly support auto importation of the email. But yay, limitations lol.
-2. No, but honestly I wouldn't recommend it as imo it's kinda tedious and pointless lol. just visiting the validating user and pressing delete works best. not sure why IPS doesnt include a delete user button on that page.
