### ISSUE TITLE
Error Code: EX0

### ISSUE THREAD

**Issue by skyprah** [Lavoaster/IP.Board-Steam-Authentication-Method#80]
When attempting to create an account with steam I get this error
"Sorry, there is a problem
Something went wrong. Please try again.
Error code: EX0"

It used to work fine

**Comment by madman32395** [comment]
What is the error associated with that ex0?

**Comment by madman32395** [comment]
@skyprah what is the error associated with the EX0? you can find these out in Support>Support>System Errors

**Comment by Terminuscentral** [comment]
Im getting this error, here are the details of the error


Exception: steam_err_noapi (0)
#0 /var/www/html/applications/steam/extensions/core/MemberSync/Steam.php(131): IPS\steam\_Update->__construct()
#1 [internal function]: IPS\steam\extensions\core\MemberSync\_Steam->onProfileUpdate(Object(IPS\Member), Array)
#2 /var/www/html/system/Member/Member.php(3146): call_user_func_array(Array, Array)
#3 /var/www/html/system/Member/Member.php(357): IPS\_Member->memberSync('onProfileUpdate', Array)
#4 /var/www/html/system/Login/Steam.php(142): IPS\_Member->save()
#5 /var/www/html/applications/core/modules/front/system/settings.php(996): IPS\Login\_Steam->authenticate(Object(IPS\Http\Url\Friendly), Object(IPS\Member))
#6 [internal function]: IPS\core\modules\front\system\_settings->_profilesync()
#7 /var/www/html/applications/core/modules/front/system/settings.php(55): call_user_func(Array)
#8 /var/www/html/system/Dispatcher/Controller.php(97): IPS\core\modules\front\system\_settings->manage()
#9 /var/www/html/applications/core/modules/front/system/settings.php(35): IPS\Dispatcher\_Controller->execute()
#10 /var/www/html/system/Dispatcher/Dispatcher.php(129): IPS\core\modules\front\system\_settings->execute()
#11 /var/www/html/index.php(13): IPS\_Dispatcher->run()
#12 {main}

**Comment by madman32395** [comment]
@Terminuscentral I would double check file and ownership permissions, redirect scripts. If both dont work, check to see if your server or firewall can ping to "api.steampowered.com"
