### ISSUE TITLE
Not Showing on Login Handlers

### ISSUE THREAD

**Issue by Ezaco** [Lavoaster/IP.Board-Steam-Authentication-Method#81]
I've uploaded the folders included, and set their directories to 777 permissions.

I've uploaded the Steam_login.xml.

The plugin shows up, but Steam Login is not on the Login Handlers page. There is an entry for it in core_login_handlers in phpMyAdmin, but it's not showing up in the AdminCP. I've even tried deleting the entry in phpMyAdmin and reinserting it as detailed in another issue, but it's still not showing up. I've logged out and logged back in to the AdminCP, and I've even restarted my server. Still not showing up. I've even tried changing it's order.

Running IPS 4.1.19.

**Comment by madman32395** [comment]
@Ezaco are you running a custom theme? Try using the default theme and seeing if the handler button returns.

**Comment by Ezaco** [comment]
On the Admin panel? It's using the default theme.

**Comment by madman32395** [comment]
no on front end.

**Comment by Ezaco** [comment]
Unfortunately the guy editing my themes used the default theme to change.. but he's only changed CSS values. Can I ask why changing the theme on the front end would determine whether or not the handler appears in the AdminCP?

**Comment by madman32395** [comment]
idk just something ive noticed that would cause conflict in the past. (as long as if the login handler appears in DB, and files are uploaded correctly.)

**Comment by Ezaco** [comment]
Makes sense. 

I'm fairly sure I've uploaded the files correctly. I'm using a Linux server but I decompressed the folder then moved the folders to the website root, and changed their permissions to 777. Then I uploaded the XML file.

**Comment by madman32395** [comment]
funny question, but did you take the stuff out of the upload folder? or do you have <ipspath>/upload/ ?

**Comment by Ezaco** [comment]
I didn't have an /upload/ folder but I have an /uploads/ folder which is where I moved the contents of the download to.

**Comment by madman32395** [comment]
ok, so you took the contents out of the upload folder when you uploaded? silly question i know. but its happened before lol

**Comment by Ezaco** [comment]
Yes, I double checked. No upload folder inside my uploads folder ;)

**Comment by madman32395** [comment]
hmm. hit me up on [steam](http://steamcommunity.com/id/madman32395). could I take a peak?

**Comment by Ezaco** [comment]
Followup from yesterday, FTP access is now working.

**Comment by madman32395** [comment]
Manual uninstall, reinstall, found a few permission errors serverside, applied 4.1.19 post patches (curl and request) tested on both registered link and new user both work on my end, had Ezaco test on their end, works for them.
