### ISSUE TITLE
No option in in Login Handlers

### ISSUE THREAD

**Issue by Fiiily** [Lavoaster/IP.Board-Steam-Authentication-Method#86]
I can't find the place where I would set my apikey under login handlers.
![image](https://user-images.githubusercontent.com/16643747/28295710-4d7a4f9e-6b28-11e7-960a-f36b247da969.png)
![image](https://user-images.githubusercontent.com/16643747/28295728-6d6b8bb0-6b28-11e7-9e5c-a55846c16ab0.png)

**Comment by madman32395** [comment]
There should be an option in login handlers for steam (top image) then click the pencil button to edit and add api key.

Make sure upload folder is uploaded properly, and xml file has been installed via plugin install.

**Comment by Fiiily** [comment]
... what folder @madman32395? I can't exactly upload folders as I use the cloud version of IPS.

**Comment by madman32395** [comment]
ah, have you had IPS support do the file upload for you yet?

**Comment by Fiiily** [comment]
They'll do that? Sweet! Alright, problem solved if they will. Thanks.

**Comment by madman32395** [comment]
yea, just tell them the plugin you want installed, they upload the upload folder... then you just install the .xml  (you have to download the plugin from either here or IPS MP).

Once uploaded and you have more issues, just let me know.

**Comment by madman32395** [comment]
assuming installed per #87
