### ISSUE TITLE
/settings/steam FURL broken

### ISSUE THREAD

**Issue by kacx9c** [Lavoaster/IP.Board-Steam-Authentication-Method#92]
You're hook is extending \IPS\Http\Url  It needs to extend \IPS\Http\Url\Friendly

furlDefinition isn't a valid method in \IPS\Http\Url, thus your hook isn't doing anything.

Try visiting /settings while IN_DEV, ;)

**Comment by madman32395** [comment]
Thanks bud ; 94ec34d
