### ISSUE TITLE
Invalid details

### ISSUE THREAD

**Issue by DimitriSES** [Lavoaster/IP.Board-Steam-Authentication-Method#95]
Installed this addon on the 27th of October last year and had no issues with the addon untill now. Installed the update for IPS CS 4.2.7 and the plugin for Steam doesn't work. When logging in through Steam it displays for everyone the error "Invalid Details". Not sure what is going on.

**Comment by DimitriSES** [comment]
![afbeelding](https://user-images.githubusercontent.com/8708568/34915477-c1e757ae-f927-11e7-94ce-3a9c22e3b8ed.png)

**Comment by Justinh4x** [comment]
Same thing here, is this it? 

![](https://i.gyazo.com/227698bfb20da4c30605da9ab1cfa1ac.png)

**Comment by Phil7789** [comment]
I just checked it now and I do not receive this error. Looks like it is a steam problem, isn't it? As it shows on the steam website, not on IPS.

**Comment by Hyrius** [comment]
It was. Globally.
