### ISSUE TITLE
Steam only login methode

### ISSUE THREAD

**Issue by Jpofin** [Lavoaster/IP.Board-Steam-Authentication-Method#96]
Well someone posted this already but I'm looking for a methode to login only with steam
I disabled the usual register/login methode but I can't find the code for the steam-button.

Does anyone know where I can find it?
I found one in the dev section but it's for the design only, no functions.

Would be nice if someone would help me with that.
I may just be blind so don't judge me please **>.>**

**Comment by Jpofin** [comment]
Where do I find the code to implement a working button on another page than this?
Only allow social media stuff and putting social media loginbuttons on the main page instead of the usual login would be good to

**Comment by madman32395** [comment]
In its current state IPS requires the Standard login hander to work all the time. But using CSS you can hide other login methods. I would recommend hitting up the theme assistance forums at https://invisioncommunity.com/forums/forum/500-theme-assistance/ someone may have a solution to "hiding" the other login methods that you want to hide.
